### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by runner-mei** [revel/revel#1064]
path=d:\developing\go\meijing\src\mc\app 
root=d:\developing\go\meijing\src/mc/app
````
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x9401e0, 0xc082004060)
        d:/tools/go_amd64/src/runtime/panic.go:481 +0x3f4
github.com/revel/cmd/harness.ProcessSource.func1(0xc08215dc20, 0x23, 0x1746b0, 0xc0821595c0, 0x0, 0x0, 0x0, 0x0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/cmd/harness/reflect.go:114 +0xe5e
github.com/revel/revel.fsWalk.func1(0xc08215dc20, 0x23, 0x1746b0, 0xc0821595c0,0x0, 0x0, 0x0, 0x0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/revel/util.go:264 +0x412
path/filepath.walk(0xc082134420, 0x23, 0x1746b0, 0xc0821595c0, 0xc08215d9e0, 0x0, 0x0)
        d:/tools/go_amd64/src/path/filepath/path.go:349 +0x87
path/filepath.Walk(0xc082134420, 0x23, 0xc08215d9e0, 0x0, 0x0)
        d:/tools/go_amd64/src/path/filepath/path.go:396 +0xe8
github.com/revel/revel.fsWalk(0xc082134420, 0x23, 0xc082134420, 0x23, 0xc08215d9b0, 0x0, 0x0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/revel/util.go:267 +0xbd
github.com/revel/revel.Walk(0xc082134420, 0x23, 0xc08215d9b0, 0x0, 0x0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/revel/util.go:215 +0x52
github.com/revel/cmd/harness.ProcessSource(0xc082079500, 0x5, 0x8, 0xcb0420, 0xc0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/cmd/harness/reflect.go:168 +0x3fe
github.com/revel/cmd/harness.Build(0x0, 0x0, 0x0, 0x0, 0x0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/cmd/harness/build.go:30 +0xfa
main.buildApp(0xc08200a420, 0x2, 0x2)
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/cmd/revel/build.go:62 +0x61c
main.main()
        d:/developing/go/meijing/tpt_vendor/src/github.com/revel/cmd/revel/rev.go:81 +0x5eb
````

**Comment by ivanzhangio** [comment]
Getting the same problem after updating to v0.13 on Windows 10. Also tried removing all revel files and using "go get" again for `revel/cmd` and `revel/revel` but to no avail.

**Comment by jeevatkm** [comment]
@ivanzhangio Can you please try this, share your feedback?

Note: Please change the path according to windows.
* Remove `$GOPATH/bin/revel`, `$GOPATH/bin/revel/revel.d/`,  `$GOPATH/src/github.com/revel` and `$GOPATH/pkg/darwin_amd64/github.com/revel`
* `go get -u github.com/revel/cmd/revel`

**Comment by ivanzhangio** [comment]
@jeevatkm same issue, unfortunately.

**Comment by jeevatkm** [comment]
I will look into it ASAP. Thanks for your quick response.

**Comment by jeevatkm** [comment]
@ivanzhangio @runner-mei Can you please take an update and verify it? 

*PS: I have applied path fix and verified in my windows 10 VM.*

**Comment by jeevatkm** [comment]
FYI, windows support will be significantly improve on `v0.14` release

**Comment by runner-mei** [comment]
it is ok.

**Comment by jeevatkm** [comment]
@runner-mei thanks for confirmation.
