### ISSUE TITLE
 failed to find controller TestRunner

### ISSUE THREAD

**Issue by nikxliu** [revel/revel#1085]
I got this problem on windows.
My go version is **1.6.2**.
Go ENV:
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\tools\Go;D:\tools\workspace\go;E:\worktools\wassupport\WASAUTO\go;D:\tools\workspace\revel;D:\tools\worksp
ace\beego;D:\tools\workspace\bluemix
set GORACE=
set GOROOT=d:\tools\Go
set GOTOOLDIR=d:\tools\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

I use this command to create the test app and run it.
```
revel new myapp
revel run myapp
```
I get the message:
```

D:\tools\workspace\revel>revel run myapp
~
~ revel! http://revel.github.io
~
INFO  2016/07/28 15:01:51 revel.go:365: Loaded module static
INFO  2016/07/28 15:01:51 revel.go:365: Loaded module testrunner
INFO  2016/07/28 15:01:51 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
INFO  2016/07/28 15:01:51 run.go:57: Running myapp (myapp) in dev mode
INFO  2016/07/28 15:01:51 harness.go:170: Listening on :9000
```

when I visit the url:http://localhost:9000/
I got the message :
```
INFO  2016/07/28 15:02:50 build.go:179: Cleaning dir tmp
INFO  2016/07/28 15:02:50 build.go:179: Cleaning dir routes
ERROR 2016/07/28 15:02:50 reflect.go:776: Unexpected! Code path is not in GOPATH: d:\tools\Go\src\github.com\revel\modul
es\static\app
WARN  2016/07/28 15:02:50 reflect.go:94: Skipping code path d:\tools\Go\src\github.com\revel\modules\static\app
ERROR 2016/07/28 15:02:50 reflect.go:776: Unexpected! Code path is not in GOPATH: d:\tools\Go\src\github.com\revel\modul
es\testrunner\app
WARN  2016/07/28 15:02:50 reflect.go:94: Skipping code path d:\tools\Go\src\github.com\revel\modules\testrunner\app
INFO  2016/07/28 15:02:50 build.go:179: Cleaning dir tmp
INFO  2016/07/28 15:02:50 build.go:179: Cleaning dir routes
INFO  2016/07/28 15:02:54 revel.go:365: Loaded module static
INFO  2016/07/28 15:02:54 revel.go:365: Loaded module testrunner
INFO  2016/07/28 15:02:54 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
INFO  2016/07/28 15:02:54 main.go:27: Running revel server
ERROR 2016/07/28 15:02:54 router.go:431: Route validation error (in d:\tools\Go\src\github.com\revel\modules\testrunner/
conf/routes:1): revel/controller: failed to find controller TestRunner
panic: Route validation error (in d:\tools\Go\src\github.com\revel\modules\testrunner/conf/routes:1): revel/controller:
failed to find controller TestRunner


goroutine 1 [running]:
panic(0x8330e0, 0xc082150bf0)
        d:/tools/Go/src/runtime/panic.go:481 +0x3f4
log.(*Logger).Panicln(0xc0820176d0, 0xc082069ac0, 0x1, 0x1)
        d:/tools/Go/src/log/log.go:220 +0xc6
github.com/revel/revel.init.4.func1()
        d:/tools/Go/src/github.com/revel/revel/router.go:431 +0x480
github.com/revel/revel.runStartupHooks()
        d:/tools/Go/src/github.com/revel/revel/server.go:164 +0xec
github.com/revel/revel.InitServer(0x923820)
        d:/tools/Go/src/github.com/revel/revel/server.go:85 +0x2b
github.com/revel/revel.Run(0xeb49)
        d:/tools/Go/src/github.com/revel/revel/server.go:137 +0x293
main.main()
        D:/tools/workspace/revel/src/myapp/app/tmp/main.go:49 +0x460
```

Can you help me !

thanks.

**Comment by jeevatkm** [comment]
@nikxliu  It looks like you have `GOROOT` path in `GOPATH` as well. So remove `D:\tools\Go` for `GOPATH` and give it try.

**Comment by nikxliu** [comment]
@jeevatkm 
thanks for you reply.
I removd the d:\tools\Go from the GOPATH properties.
the new GO ENV was 
```
D:\tools\workspace\revel>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\tools\workspace\go;E:\worktools\wassupport\WASAUTO\go;D:\tools\workspace\revel;D:\tools\workspace\beego;D:
\tools\workspace\bluemix
set GORACE=
set GOROOT=d:\tools\Go
set GOTOOLDIR=d:\tools\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

**But the issue occured again.**

So I try to remove other values from GOPATH
Let it is 
```
C:\Users\Liuxuandong>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\tools\workspace\revel
set GORACE=
set GOROOT=d:\tools\Go
set GOTOOLDIR=d:\tools\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

It did not work.

**Comment by nikxliu** [comment]
I modify the method `importPathFromPath` in the file `D:\tools\Go\src\github.com\revel\cmd\harness\reflect.go`

add some additional output

```
func importPathFromPath(root string) string {
	
	for _, gopath := range filepath.SplitList(build.Default.GOPATH) {
		srcPath := filepath.Join(gopath, "src")
		revel.WARN.Println("the root is :",root)
		revel.WARN.Println("the srcPath is :",srcPath)
		if strings.HasPrefix(root, srcPath) {
			return filepath.ToSlash(root[len(srcPath)+1:])
		}
	}

	srcPath := filepath.Join(build.Default.GOROOT, "src", "pkg")
	revel.WARN.Println("1the root is :",root)
	revel.WARN.Println("1the srcPath is :",srcPath)
	if strings.HasPrefix(root, srcPath) {
		revel.WARN.Println("Code path should be in GOPATH, but is in GOROOT:", root)
		return filepath.ToSlash(root[len(srcPath)+1:])
	}

	revel.ERROR.Println("Unexpected! Code path is not in GOPATH:", root)
	return ""
}
```
After that I use the followed command rebuild the revel command .

`go install github.com\revel\cmd\revel`

```
D:\tools\workspace\revel>revel run myapp
~
~ revel! http://revel.github.io
~
INFO  2016/07/29 09:29:08 revel.go:365: Loaded module static
INFO  2016/07/29 09:29:08 revel.go:365: Loaded module testrunner
INFO  2016/07/29 09:29:08 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
INFO  2016/07/29 09:29:08 run.go:57: Running myapp (myapp) in dev mode
INFO  2016/07/29 09:29:08 harness.go:170: Listening on :9000
INFO  2016/07/29 09:29:10 build.go:179: Cleaning dir tmp
INFO  2016/07/29 09:29:10 build.go:180: Cleaning dir111 tmp
INFO  2016/07/29 09:29:10 build.go:179: Cleaning dir routes
INFO  2016/07/29 09:29:10 build.go:180: Cleaning dir111 routes
WARN  2016/07/29 09:29:10 reflect.go:766: the root is : D:\tools\workspace\revel\src\myapp\app
WARN  2016/07/29 09:29:10 reflect.go:767: the srcPath is : D:\tools\workspace\go\src
WARN  2016/07/29 09:29:10 reflect.go:766: the root is : D:\tools\workspace\revel\src\myapp\app
WARN  2016/07/29 09:29:10 reflect.go:767: the srcPath is : E:\worktools\wassupport\WASAUTO\go\src
WARN  2016/07/29 09:29:10 reflect.go:766: the root is : D:\tools\workspace\revel\src\myapp\app
WARN  2016/07/29 09:29:10 reflect.go:767: the srcPath is : D:\tools\workspace\revel\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\go\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : E:\worktools\wassupport\WASAUTO\go\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\revel\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\beego\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\bluemix\src
WARN  2016/07/29 09:29:11 reflect.go:774: 1the root is : d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:775: 1the srcPath is : d:\tools\Go\src\pkg
ERROR 2016/07/29 09:29:11 reflect.go:781: Unexpected! Code path is not in GOPATH: d:\tools\Go\src\github.com\revel\modul
es\static\app
WARN  2016/07/29 09:29:11 reflect.go:94: Skipping code path d:\tools\Go\src\github.com\revel\modules\static\app
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\go\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : E:\worktools\wassupport\WASAUTO\go\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\revel\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\beego\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\bluemix\src
WARN  2016/07/29 09:29:11 reflect.go:774: 1the root is : d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:775: 1the srcPath is : d:\tools\Go\src\pkg
ERROR 2016/07/29 09:29:11 reflect.go:781: Unexpected! Code path is not in GOPATH: d:\tools\Go\src\github.com\revel\modul
es\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:94: Skipping code path d:\tools\Go\src\github.com\revel\modules\testrunner\app
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : D:\tools\workspace\revel\src\myapp\tests
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\go\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : D:\tools\workspace\revel\src\myapp\tests
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : E:\worktools\wassupport\WASAUTO\go\src
WARN  2016/07/29 09:29:11 reflect.go:766: the root is : D:\tools\workspace\revel\src\myapp\tests
WARN  2016/07/29 09:29:11 reflect.go:767: the srcPath is : D:\tools\workspace\revel\src
INFO  2016/07/29 09:29:11 build.go:179: Cleaning dir tmp
INFO  2016/07/29 09:29:11 build.go:180: Cleaning dir111 tmp
INFO  2016/07/29 09:29:11 build.go:179: Cleaning dir routes
INFO  2016/07/29 09:29:11 build.go:180: Cleaning dir111 routes
INFO  2016/07/29 09:29:15 revel.go:365: Loaded module testrunner
INFO  2016/07/29 09:29:15 revel.go:365: Loaded module static
INFO  2016/07/29 09:29:15 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
INFO  2016/07/29 09:29:15 main.go:27: Running revel server
ERROR 2016/07/29 09:29:15 router.go:431: Route validation error (in d:\tools\Go\src\github.com\revel\modules\testrunner/
conf/routes:1): revel/controller: failed to find controller TestRunner
panic: Route validation error (in d:\tools\Go\src\github.com\revel\modules\testrunner/conf/routes:1): revel/controller:
failed to find controller TestRunner


goroutine 1 [running]:
panic(0x8330e0, 0xc082158ad0)
        d:/tools/Go/src/runtime/panic.go:481 +0x3f4
log.(*Logger).Panicln(0xc0820156d0, 0xc082069ac0, 0x1, 0x1)
        d:/tools/Go/src/log/log.go:220 +0xc6
github.com/revel/revel.init.4.func1()
        d:/tools/Go/src/github.com/revel/revel/router.go:431 +0x480
github.com/revel/revel.runStartupHooks()
        d:/tools/Go/src/github.com/revel/revel/server.go:164 +0xec
github.com/revel/revel.InitServer(0x923820)
        d:/tools/Go/src/github.com/revel/revel/server.go:85 +0x2b
github.com/revel/revel.Run(0xc9e9)
        d:/tools/Go/src/github.com/revel/revel/server.go:137 +0x293
main.main()
        D:/tools/workspace/revel/src/myapp/app/tmp/main.go:49 +0x460
```

I found the followed message in the output.

**WARN  2016/07/29 09:29:11 reflect.go:774: 1the root is : d:\tools\Go\src\github.com\revel\modules\static\app**
**WARN  2016/07/29 09:29:11 reflect.go:775: 1the srcPath is : d:\tools\Go\src\pkg**

the word "**pkg**" is the root cause

So I modify the method in the file `D:\tools\Go\src\github.com\revel\cmd\harness\reflect.go`

remove the word "**pkg**"

```
func importPathFromPath(root string) string {
	
	for _, gopath := range filepath.SplitList(build.Default.GOPATH) {
		srcPath := filepath.Join(gopath, "src")
		if strings.HasPrefix(root, srcPath) {
			return filepath.ToSlash(root[len(srcPath)+1:])
		}
	}

	srcPath := filepath.Join(build.Default.GOROOT, "src")
	if strings.HasPrefix(root, srcPath) {
		revel.WARN.Println("Code path should be in GOPATH, but is in GOROOT:", root)
		return filepath.ToSlash(root[len(srcPath)+1:])
	}

	revel.ERROR.Println("Unexpected! Code path is not in GOPATH:", root)
	return ""
}
```

I rebuild the revel command again and run the command "revel run myapp"
Now it works.

**Comment by brendensoares** [comment]
[relevant code](https://github.com/revel/cmd/blob/master/harness/reflect.go#L770)

@nikxliu I'm just jumping in here, but can this issue be reproduced with a new Revel app or is it specific to your code base?

**Comment by nikxliu** [comment]
My revel version:
```
C:\Users\Liuxuandong>revel version
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.13.1 (2016-06-06)
   go1.6.2 windows/amd64
```

I upload `myapp` which is my test app's name.
[revel.zip](https://github.com/revel/revel/files/390121/revel.zip)

**Are you running in dev or prod mode?**
Sorry I can not answer this question. 
But I use the guide to install, create and run the revel app. I did not modify any configure file in the revel app.

**Comment by jeevatkm** [comment]
@nikxliu If you didn't modify any configs, you're running revel in `dev` mode.

From your details, you're facing issue of `GOROOT` and `GOPATH` conflict. Please refer http://golang.org/doc/code.html 

As @brendensoares mentioned, code change is not required to sort out this issue.

Kindly make distinguish between `GOROOT` and `GOPATH` in your environment and keep your revel app in `GOPATH`. Your program will surely work.

Please let me know.

**Comment by nikxliu** [comment]
@jeevatkm @brendensoares 
Thank you very much.

I remove the `d:\tools\Go` from `GOPATH` and re-install the `revel`.

`myapp` works.

**Comment by jeevatkm** [comment]
@nikxliu glad to hear!
