### ISSUE TITLE
Unable to show error string with log15

### ISSUE THREAD

**Issue by hsluoyz** [revel/revel#1232]
I'm developing and debugging a revel module ``revel/modules/auth``, and then caused this error. In fact the error string is ``default addr for network '127.0.0.1:3306' unknown`` but it is not shown in the GoGland console output. I have to find it by debugging the err variable. I think this is a bug that error printing library log15 used by revel doesn't print error string well as below:

```
panic: interface conversion: interface {} is *errors.errorString, not string
```

Since  ``github.com/revel/log15`` doesn't have issue page, so I have to post this issue here.

```
GOROOT=C:/Go
GOPATH=C:/GoPath
C:/Go\bin\go.exe test -c -i -o C:\Users\Administrator\AppData\Local\Temp\___TestBasic_in_authz_test_go.exe github.com/revel/modules/auth/casbin
"C:\Program Files\JetBrains\Gogland 172.3757.2\bin\runnerw.exe" C:\Users\Administrator\AppData\Local\Temp\___TestBasic_in_authz_test_go.exe -test.v -test.run ^TestBasic$

DEBUG 23:24:38  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 

panic: interface conversion: interface {} is *errors.errorString, not string

goroutine 1 [running]:

github.com/revel/revel/logger.findInContext(0x9f87d0, 0x6, 0xc0420ba780, 0x8, 0xc, 0x412861, 0x1c58f0)

	C:/GoPath/src/github.com/revel/revel/logger/format.go:102 +0x152

github.com/revel/revel/logger.TerminalFormatHandler.func1(0xc0421fe1b0, 0xc04202a000, 0xc042052000, 0xc000000076)

	C:/GoPath/src/github.com/revel/revel/logger/format.go:58 +0x122

github.com/revel/log15.formatFunc.Format(0xc0421ad640, 0xc0421fe1b0, 0xc04201f370, 0xc04201f300, 0x16b0678)

	C:/GoPath/src/github.com/revel/log15/format.go:34 +0x37

github.com/revel/log15.StreamHandler.func1(0xc0421fe1b0, 0xc04224d900, 0xa20490)

	C:/GoPath/src/github.com/revel/log15/handler.go:43 +0x56

github.com/revel/log15.funcHandler.Log(0xc0421c7ad0, 0xc0421fe1b0, 0xc0422a4058, 0x467bc9)

	C:/GoPath/src/github.com/revel/log15/handler.go:31 +0x37

github.com/revel/log15.SyncHandler.func1(0xc0421fe1b0, 0x0, 0x0)

	C:/GoPath/src/github.com/revel/log15/handler.go:57 +0xa2

github.com/revel/log15.funcHandler.Log(0xc0421ad660, 0xc0421fe1b0, 0x0, 0x400420b1480)

	C:/GoPath/src/github.com/revel/log15/handler.go:31 +0x37

github.com/revel/log15.LazyHandler.func1(0xc0421fe1b0, 0xc0420ba780, 0xc0420ba3c0)

	C:/GoPath/src/github.com/revel/log15/handler.go:295 +0x341

github.com/revel/log15.funcHandler.Log(0xc0421ad680, 0xc0421fe1b0, 0x6, 0x6)

	C:/GoPath/src/github.com/revel/log15/handler.go:31 +0x37

github.com/revel/log15.CallerFileHandler.func1(0xc0421fe1b0, 0x90, 0x88)

	C:/GoPath/src/github.com/revel/log15/handler.go:101 +0x192

github.com/revel/log15.funcHandler.Log(0xc0421ad6a0, 0xc0421fe1b0, 0x88, 0xc0421fe1b0)

	C:/GoPath/src/github.com/revel/log15/handler.go:31 +0x37

github.com/revel/revel/logger.(*CompositeMultiHandler).Log(0xc042149f40, 0xc0421fe1b0, 0x1c06a8, 0x0)

	C:/GoPath/src/github.com/revel/revel/logger/handlers.go:207 +0x79

github.com/revel/log15.(*swapHandler).Log(0xc0421c0690, 0xc0421fe1b0, 0x90, 0x9b87c0)

	C:/GoPath/src/github.com/revel/log15/handler_go14.go:14 +0x95

github.com/revel/log15.(*swapHandler).Log(0xc0421c0810, 0xc0421fe1b0, 0x8b9f04, 0xc0421c1bb0)

	C:/GoPath/src/github.com/revel/log15/handler_go14.go:14 +0x95

github.com/revel/log15.(*logger).write(0xc0421c6fc0, 0x9ffbae, 0xf, 0x0, 0xc0421c1bb0, 0x1, 0x1)

	C:/GoPath/src/github.com/revel/log15/logger.go:108 +0x249

github.com/revel/log15.(*logger).Crit(0xc0421c6fc0, 0x9ffbae, 0xf, 0xc0421c1bb0, 0x1, 0x1)

	C:/GoPath/src/github.com/revel/log15/logger.go:162 +0x6d

github.com/revel/revel/logger.(*RevelLogger).Fatal(0xc0421c0830, 0x9ffbae, 0xf, 0xc0421c1bb0, 0x1, 0x1)

	C:/GoPath/src/github.com/revel/revel/logger/logger.go:143 +0x6c

github.com/revel/modules/orm/gorm/app.OpenDB(0x9f7cc4, 0x5, 0xc0420884b0, 0x41)

	C:/GoPath/src/github.com/revel/modules/orm/gorm/app/gorm.go:33 +0x175

github.com/revel/modules/orm/gorm/app.InitDBWithParameters(0x9f7cc4, 0x5, 0x9fe75b, 0xe, 0x9f6dc6, 0x4, 0x0, 0x0, 0x9f87e2, 0x6)

	C:/GoPath/src/github.com/revel/modules/orm/gorm/app/gorm.go:56 +0xe6

github.com/revel/modules/auth/casbin.NewAdapter(0x9f7cc4, 0x5, 0x9fe75b, 0xe, 0x9f6dc6, 0x4, 0x0, 0x0, 0x9f87e2, 0x6, ...)

	C:/GoPath/src/github.com/revel/modules/auth/casbin/adapter.go:32 +0x62

github.com/revel/modules/auth/casbin.init()

	C:/GoPath/src/github.com/revel/modules/auth/casbin/authz_test.go:16 +0xdd

main.init()

	<autogenerated>:1 +0x5a

Process finished with exit code 2
```

**Comment by notzippy** [comment]
Logging now has a context option to it - (see https://github.com/revel/revel/pull/1213)
I just fixed it so if you do a git update you should get the patch
https://github.com/revel/modules/commit/3f777980cd94fa4c59b25e3ba9a4f0f616d64cf3
