### ISSUE TITLE
Using GOPATH instead of GOROOT for 

### ISSUE THREAD

**Issue by efimovalex** [revel/revel#1266]
Hello,

I am getting an error while running revel app inside a docker container. Any idea what might be causing it?
Seems someone had a similar issue here: https://stackoverflow.com/questions/46677237/golang-revel-assertf-causes-panic

```
revel run github.com/user/app dev 8080
```

```
INFO  21:49:46  revel harness.go:190: Listening on :8080
INFO  21:49:49    app server.go:2848: http: panic serving 127.0.0.1:41832: open /go/src/runtime/debug/stack.go: no such file or directory
goroutine 272 [running]:
net/http.(*conn).serve.func1(0xc420154000)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x9bc1a0, 0xc42033de00)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.MustReadLines(0xc420395852, 0x1e, 0x1, 0xc4202d8e80, 0x40)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/util.go:55 +0x83
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.NewErrorFromPanic(0x9c6480, 0xf361c0, 0x431a18)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/errors.go:63 +0x24e
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.handleInvocationPanic(0xc4202eec30, 0x9c6480, 0xf361c0)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/panic.go:26 +0x39
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.PanicFilter.func1(0xc4202eec30)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/panic.go:17 +0x4d
panic(0x9c6480, 0xf361c0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.InterceptorFilter.func1(0xc4202eec30)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/intercept.go:98 +0x7d
panic(0x9c6480, 0xf361c0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/efimovalex/produselocale/vendor/github.com/jinzhu/gorm.(*DB).clone(0x0, 0xa45f40)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/jinzhu/gorm/main.go:670 +0x76
github.com/efimovalex/produselocale/vendor/github.com/jinzhu/gorm.(*DB).Begin(0x0, 0xc42033dce0)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/jinzhu/gorm/main.go:421 +0x2f
github.com/efimovalex/produselocale/vendor/github.com/Gr1N/revel-gorm/app/controllers.(*TransactionalController).Begin(0xc42032f328, 0x0, 0x0)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/Gr1N/revel-gorm/app/controllers/db.go:19 +0x31
reflect.Value.call(0x9a5d00, 0xa7d728, 0x13, 0xa58617, 0x4, 0xc42033b2a8, 0x1, 0x1, 0x2, 0xfffffffffffffffe, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x9a5d00, 0xa7d728, 0x13, 0xc42033b2a8, 0x1, 0x1, 0xc42033dc80, 0xc420289120, 0xc42026fec0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.Interception.Invoke(0x0, 0x0, 0x9a5d00, 0xa7d728, 0x9a5d00, 0xa7d728, 0x13, 0xf55e00, 0xa45f40, 0x0, ...)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/intercept.go:89 +0x18c
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.invokeInterceptors(0x0, 0xc4202eec30)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/intercept.go:119 +0x17a
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.InterceptorFilter(0xc4202eec30, 0xc420254410, 0x2, 0x2)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/intercept.go:103 +0x95
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.I18nFilter(0xc4202eec30, 0xc420254408, 0x3, 0x3)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/i18n.go:212 +0xa1
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.ValidationFilter(0xc4202eec30, 0xc420254400, 0x4, 0x4)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/validation.go:269 +0x19b
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.FlashFilter(0xc4202eec30, 0xc4202543f8, 0x5, 0x5)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/flash.go:50 +0x13c
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.SessionFilter(0xc4202eec30, 0xc4202543f0, 0x6, 0x6)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/session.go:158 +0x117
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.ParamsFilter(0xc4202eec30, 0xc4202543e8, 0x7, 0x7)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/params.go:179 +0xb1
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.FilterConfiguringFilter(0xc4202eec30, 0xc4202543e0, 0x8, 0x8)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/filterconfig.go:211 +0x126
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.RouterFilter(0xc4202eec30, 0xc4202543d8, 0x9, 0x9)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/router.go:789 +0x414
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.PanicFilter(0xc4202eec30, 0xc4202543d0, 0xa, 0xa)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/panic.go:20 +0x93
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.glob..func32(0xc4202eec30, 0xc4202543c8, 0xb, 0xb)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/watcher.go:222 +0x7d
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.handleInternal(0xf4c700, 0xc42032d2e0)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/server-engine.go:145 +0x3cd
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.(*GoHttpServer).Handle(0xc420308b40, 0xf4fbc0, 0xc420012380, 0xc4203ee100)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/server_adapter_go.go:101 +0x39e
github.com/efimovalex/produselocale/vendor/github.com/revel/revel.(*GoHttpServer).Init.func3(0xf4fbc0, 0xc420012380, 0xc4203ee100)
	/go/src/github.com/efimovalex/produselocale/vendor/github.com/revel/revel/server_adapter_go.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203246b0, 0xf4fbc0, 0xc420012380, 0xc4203ee100)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc4202ee410, 0xf4fbc0, 0xc420012380, 0xc4203ee100)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420154000, 0xf50480, 0xc420368000)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288  section=system
INFO  21:49:49    app reverseproxy.go:324: http: proxy error: EOF                    section=system
```

**Comment by notzippy** [comment]
The panic filter is failing because it cannot locate the source file of the go code that caused the error. If you have stripped away the source files from the deployment this could cause that (IMHO it really shouldn't) but looking at the code it is attempting to load up the file which the stack says has the error on it. 

If you remove the `revel.PanicFilter` from app/init.go you should see the cause of the real cause of the error.

**Comment by efimovalex** [comment]
Thanks, that helped.

**Comment by pault84** [comment]
@efimovalex what ended up being the issue? i'm having literally the same issue right now.

**Comment by efimovalex** [comment]
I had an issue with the GORM database while saving a struct.
