### ISSUE TITLE
Accessing UI running in container throws a panic

### ISSUE THREAD

**Issue by pault84** [revel/revel#1280]
The second i try to hit my ui on any page. it throws below stack. I disabled the panicfilter as suggested in another thread similar to this.

Below lines are the culprit of the panic it seems my module returns nil.
This works fine if i run the server manually outside of a container.
`
        println("Returned ", module)
        action := module.Namespace() + recvType.Name() + "." + method.Name
`

Stack:
`
    Listening on.. localhost:80

    Returned  0x0
    INFO  22:49:29    app server.go:2753: http: panic serving 127.0.0.1:47290: runtime error: invalid memory address or nil pointer dereference
    goroutine 40 [running]:
    net/http.(*conn).serve.func1(0xc42019e000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
    panic(0xc223c0, 0x13b7390)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
    github.com/revel/revel.getRedirectURL(0xbe7ec0, 0xd53e98, 0x0, 0x0, 0x0, 0x708699, 
    0xcab3e0, 0xc4205163b0, 0x6)
	/go/src/github.com/revel/revel/results.go:472 +0x271
    github.com/revel/revel.(*RedirectToActionResult).Apply(0xc42058aff0, 0xc4203b5d40, 
    0xc4203fd900)
	/go/src/github.com/revel/revel/results.go:439 +0x5c
    github.com/revel/revel.handleInternal(0x13d09a0, 0xc420411de0)
	/go/src/github.com/revel/revel/server-engine.go:147 +0x9cc
    github.com/revel/revel.(*GoHttpServer).Handle(0xc42040c570, 0x13d4da0, 0xc420122380, 
    0xc4201fc200)
	/go/src/github.com/revel/revel/server_adapter_go.go:101 +0x239
    github.com/revel/revel.(*GoHttpServer).Init.func3(0x13d4da0, 0xc420122380, 0xc4201fc200)
	/go/src/github.com/revel/revel/server_adapter_go.go:43 +0x48
    net/http.HandlerFunc.ServeHTTP(0xc4204038d0, 0x13d4da0, 0xc420122380, 0xc4201fc200)
	/usr/local/go/src/net/http/server.go:1942 +0x44
    net/http.serverHandler.ServeHTTP(0xc420241d90, 0x13d4da0, 0xc420122380, 
    0xc4201fc200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
    net/http.(*conn).serve(0xc42019e000, 0x13d5c60, 0xc42048a000)
	/usr/local/go/src/net/http/server.go:1825 +0x612
    created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce  section=system
`

Any idea what i'm doing wrong? this was all working on revel 0.17.0

**Comment by pault84** [comment]
Looks like this might actually be a dupe of Issue #1263 
going to try to change my redirects and see

**Comment by pault84** [comment]
Ok so i'm out of the woods but i still don't understand why i had to change all my redirects.

**Comment by lujiacn** [comment]
how you defined your redirect route? If only use "c.Redirect(App.Index)" will introduce the error (but works fine before 0.18. The same way to use "c.Redirect(routes.App.Index())", works before and after 0.18. Just need import app routes.

**Comment by pault84** [comment]
I tried both ways. routes.App.Index and /app/index  and (*App).Index

routes.App.Index() throws an error.

**Comment by lujiacn** [comment]
routes.App.Index() is format, you should using your own type and func names. If routes.App.Index() function throws error, check your defined controller and functions. it should return a url string.

I noticed you run app in container, set http.address= 0.0.0.0 in app.conf to listen all ip address (coming).
And another issue (0.18) is do not set "result.compressed = true" keep it false (default is false).

**Comment by notzippy** [comment]
@lujiacn The `results.compressed` config option should be fixed now.

I will check into seeing why the routes.App.Index() is breaking things

**Comment by lujiacn** [comment]
@notzippy Great! Thanks :)
