### ISSUE TITLE
Panic occurred in binding form data to map[string]string

### ISSUE THREAD

**Issue by acegishniz** [revel/revel#1285]
I have Issues after this commit: f8ae517 , When I send data form in this structure , and want to bind this posted data from html form to map I get following error:

html form data:
`<input name="invisible[32ffb9e6-92d2-11e7-b1bf-54a050de5eca]" value="on" type="checkbox" >
`
in Controller I want to bind in map:

```
var invisible map[string]string
c.Params.Bind(&invisible, "invisible")

```

this panic occurred;
```
Runtime Panic
runtime error: slice bounds out of range
```

stack trace: 

```
Call Stack

/home/acegishniz/gowork/src/github.com/vada/wedio/app/controllers/admin/CategoryController.go:267 +0xd8
github.com/vada/wedio/app/controllers/admin.(*CategoryController).PostBatchEdit(0xc420318680, 0xc420b057cd, 0x24, 0x0, 0x0)
	<autogenerated>:605 +0x81
reflect.Value.call(0xb165a0, 0xc420318680, 0x4e13, 0xb1cdbd, 0x4, 0xc4203776c0, 0x1, 0x1, 0xa41660, 0xa41601, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xb165a0, 0xc420318680, 0x4e13, 0xc4203776c0, 0x1, 0x1, 0x0, 0x1, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/revel/revel.ActionInvoker(0xc4203e7e10, 0xc420720508, 0x0, 0x0)
	/home/acegishniz/gowork/src/github.com/revel/revel/invoker.go:45 +0x632
github.com/revel/revel.CompressFilter(0xc4203e7e10, 0xc420720508, 0x1, 0x1)
	/home/acegishniz/gowork/src/github.com/revel/revel/compress.go:84 +0x9e
github.com/revel/revel.InterceptorFilter(0xc4203e7e10, 0xc420720500, 0x2, 0x2)
	/home/acegishniz/gowork/src/github.com/revel/revel/intercept.go:108 +0xee
github.com/vada/wedio/app.glob..func2(0xc4203e7e10, 0xc4207204f8, 0x3, 0x3)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/init.go:200 +0x19b
github.com/vada/wedio/app.glob..func1(0xc4203e7e10, 0xc4207204f0, 0x4, 0x4)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/init.go:192 +0x146
github.com/revel/revel.I18nFilter(0xc4203e7e10, 0xc4207204e8, 0x5, 0x5)
	/home/acegishniz/gowork/src/github.com/revel/revel/i18n.go:212 +0x2ff
github.com/revel/revel.ValidationFilter(0xc4203e7e10, 0xc4207204e0, 0x6, 0x6)
	/home/acegishniz/gowork/src/github.com/revel/revel/validation.go:269 +0x1b5
github.com/vada/wedio/app/modules/revel-csrf.glob..func1(0xc4203e7e10, 0xc4207204d8, 0x7, 0x7)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/modules/revel-csrf/csrf.go:99 +0x333
github.com/vada/wedio/app/filters.SkipCsrfForApiCall(0xc4203e7e10, 0xc4207204d0, 0x8, 0x8)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/filters/skipcsrf.go:18 +0x114
github.com/vada/wedio/app/filters.RateLimiterFilter(0xc4203e7e10, 0xc4207204c8, 0x9, 0x9)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/filters/limiter.go:16 +0x78f
github.com/revel/revel.FlashFilter(0xc4203e7e10, 0xc4207204c0, 0xa, 0xa)
	/home/acegishniz/gowork/src/github.com/revel/revel/flash.go:50 +0x138
github.com/revel/revel.SessionFilter(0xc4203e7e10, 0xc4207204b8, 0xb, 0xb)
	/home/acegishniz/gowork/src/github.com/revel/revel/session.go:158 +0x126
github.com/revel/revel.ParamsFilter(0xc4203e7e10, 0xc4207204b0, 0xc, 0xc)
	/home/acegishniz/gowork/src/github.com/revel/revel/params.go:179 +0xb2
github.com/revel/revel.FilterConfiguringFilter(0xc4203e7e10, 0xc4207204a8, 0xd, 0xd)
	/home/acegishniz/gowork/src/github.com/revel/revel/filterconfig.go:211 +0x128
github.com/vada/wedio/app/controllers/admin.glob..func1(0xc4203e7e10, 0xc4207204a0, 0xe, 0xe)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/controllers/admin/AppDashboardController.go:62 +0xcf
github.com/revel/revel.RouterFilter(0xc4203e7e10, 0xc420720498, 0xf, 0xf)
	/home/acegishniz/gowork/src/github.com/revel/revel/router.go:789 +0x2cc
github.com/revel/revel.PanicFilter(0xc4203e7e10, 0xc420720490, 0x10, 0x10)
	/home/acegishniz/gowork/src/github.com/revel/revel/panic.go:20 +0x94
github.com/revel/revel.glob..func32(0xc4203e7e10, 0xc420720488, 0x11, 0x11)
	/home/acegishniz/gowork/src/github.com/revel/revel/watcher.go:222 +0x7a
github.com/revel/revel.handleInternal(0xe647a0, 0xc4203ed6c0)
	/home/acegishniz/gowork/src/github.com/revel/revel/server-engine.go:145 +0x4d8
github.com/revel/revel.(*GoHttpServer).Handle(0xc4203cdd10, 0xe67b60, 0xc420193930, 0xc4203d6b40)
	/home/acegishniz/gowork/src/github.com/revel/revel/server_adapter_go.go:101 +0x2ef
github.com/revel/revel.(*GoHttpServer).Init.func3(0xe67b60, 0xc420193930, 0xc4203d6b40)
	/home/acegishniz/gowork/src/github.com/revel/revel/server_adapter_go.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203e4360, 0xe67b60, 0xc420193930, 0xc4203d6b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203f2000, 0xe67b60, 0xc420193930, 0xc4203d6b40)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4203bfa00, 0xe68460, 0xc4202df340)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by notzippy** [comment]
The panic filter is hiding the real cause, can you comment it out and post your results again ? 
Also I updated revel a couple of days ago which may print more details - do a `go get -u github.com/revel/cmd/revel` before running to include this.
thanks

**Comment by acegishniz** [comment]
I have commented panic filter and update revel with `go get -u github.com/revel/cmd/revel
`
output:
```
goroutine 147 [running]:
net/http.(*conn).serve.func1(0xc420328280)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xa6f160, 0xc420010180)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/revel/revel.InterceptorFilter.func1(0xc4203fc1a0)
	/home/acegishniz/gowork/src/github.com/revel/revel/intercept.go:98 +0x7d
panic(0xa6f160, 0xc420010180)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/revel/revel.bindMap(0xc420391ce0, 0xb1d2aa, 0x9, 0xe671a0, 0xa6c740, 0x16, 0xa28280, 0xc420295db0)
	/home/acegishniz/gowork/src/github.com/revel/revel/binder.go:436 +0x50f
github.com/revel/revel.Bind(0xc420391ce0, 0xb1d2aa, 0x9, 0xe671a0, 0xa6c740, 0x195, 0xab37f321c9a7526, 0xe899c0)
	/home/acegishniz/gowork/src/github.com/revel/revel/binder.go:463 +0x7d
github.com/revel/revel.(*Params).Bind(0xc420391ce0, 0xa28280, 0xc420295db0, 0xb1d2aa, 0x9)
	/home/acegishniz/gowork/src/github.com/revel/revel/params.go:100 +0x161
github.com/vada/wedio/app/controllers/admin.CategoryController.PostBatchEdit(0xc4203fc1a0, 0x0, 0x0, 0x0, 0xc420b92aad, 0x24, 0x0, 0x0)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/controllers/admin/CategoryController.go:267 +0xd8
github.com/vada/wedio/app/controllers/admin.(*CategoryController).PostBatchEdit(0xc4203dd960, 0xc420b92aad, 0x24, 0x0, 0x0)
	<autogenerated>:605 +0x81
reflect.Value.call(0xb111e0, 0xc4203dd960, 0x4e13, 0xb179f5, 0x4, 0xc4202d4e40, 0x1, 0x1, 0xa3cd00, 0xa3cd01, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xb111e0, 0xc4203dd960, 0x4e13, 0xc4202d4e40, 0x1, 0x1, 0x0, 0x1, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/revel/revel.ActionInvoker(0xc4203fc1a0, 0xc42008c358, 0x0, 0x1)
	/home/acegishniz/gowork/src/github.com/revel/revel/invoker.go:45 +0x632
github.com/revel/revel.CompressFilter(0xc4203fc1a0, 0xc42008c350, 0x1, 0x2)
	/home/acegishniz/gowork/src/github.com/revel/revel/compress.go:84 +0x9e
github.com/revel/revel.InterceptorFilter(0xc4203fc1a0, 0xc42008c348, 0x2, 0x3)
	/home/acegishniz/gowork/src/github.com/revel/revel/intercept.go:108 +0xee
github.com/vada/wedio/app.glob..func2(0xc4203fc1a0, 0xc42008c340, 0x3, 0x4)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/init.go:200 +0x19b
github.com/vada/wedio/app.glob..func1(0xc4203fc1a0, 0xc42008c338, 0x4, 0x5)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/init.go:192 +0x146
github.com/revel/revel.I18nFilter(0xc4203fc1a0, 0xc42008c330, 0x5, 0x6)
	/home/acegishniz/gowork/src/github.com/revel/revel/i18n.go:212 +0x2ff
github.com/revel/revel.ValidationFilter(0xc4203fc1a0, 0xc42008c328, 0x6, 0x7)
	/home/acegishniz/gowork/src/github.com/revel/revel/validation.go:269 +0x1b5
github.com/vada/wedio/app/modules/revel-csrf.glob..func1(0xc4203fc1a0, 0xc42008c320, 0x7, 0x8)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/modules/revel-csrf/csrf.go:99 +0x333
github.com/vada/wedio/app/filters.SkipCsrfForApiCall(0xc4203fc1a0, 0xc42008c318, 0x8, 0x9)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/filters/skipcsrf.go:18 +0x114
github.com/vada/wedio/app/filters.RateLimiterFilter(0xc4203fc1a0, 0xc42008c310, 0x9, 0xa)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/filters/limiter.go:16 +0x78f
github.com/revel/revel.FlashFilter(0xc4203fc1a0, 0xc42008c308, 0xa, 0xb)
	/home/acegishniz/gowork/src/github.com/revel/revel/flash.go:50 +0x138
github.com/revel/revel.SessionFilter(0xc4203fc1a0, 0xc42008c300, 0xb, 0xc)
	/home/acegishniz/gowork/src/github.com/revel/revel/session.go:158 +0x126
github.com/revel/revel.ParamsFilter(0xc4203fc1a0, 0xc42008c2f8, 0xc, 0xd)
	/home/acegishniz/gowork/src/github.com/revel/revel/params.go:179 +0xb2
github.com/revel/revel.FilterConfiguringFilter(0xc4203fc1a0, 0xc42008c2f0, 0xd, 0xe)
	/home/acegishniz/gowork/src/github.com/revel/revel/filterconfig.go:211 +0x128
github.com/vada/wedio/app/controllers/admin.glob..func1(0xc4203fc1a0, 0xc42008c2e8, 0xe, 0xf)
	/home/acegishniz/gowork/src/github.com/vada/wedio/app/controllers/admin/AppDashboardController.go:62 +0xcf
github.com/revel/revel.RouterFilter(0xc4203fc1a0, 0xc42008c2e0, 0xf, 0x10)
	/home/acegishniz/gowork/src/github.com/revel/revel/router.go:789 +0x2cc
github.com/revel/revel.glob..func32(0xc4203fc1a0, 0xc42008c2d8, 0x10, 0x11)
	/home/acegishniz/gowork/src/github.com/revel/revel/watcher.go:222 +0x7a
github.com/revel/revel.handleInternal(0xe5d7e0, 0xc4203fada0)
	/home/acegishniz/gowork/src/github.com/revel/revel/server-engine.go:145 +0x4d8
github.com/revel/revel.(*GoHttpServer).Handle(0xc4203dbce0, 0xe60ba0, 0xc420978c30, 0xc420b28d20)
	/home/acegishniz/gowork/src/github.com/revel/revel/server_adapter_go.go:101 +0x2ef
github.com/revel/revel.(*GoHttpServer).Init.func3(0xe60ba0, 0xc420978c30, 0xc420b28d20)
	/home/acegishniz/gowork/src/github.com/revel/revel/server_adapter_go.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203ec500, 0xe60ba0, 0xc420978c30, 0xc420b28d20)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203ee100, 0xe60ba0, 0xc420978c30, 0xc420b28d20)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420328280, 0xe614a0, 0xc420655c00)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d  section=system 
INFO  10:35:23    app reverseproxy.go:279: http: proxy error: EOF                    section=system 

```

**Comment by brendensoares** [comment]
@acegishniz I used your example code and tried to reproduce the issue, but it worked as expected.

Have you tried to isolate the code from the rest of your app to see if it still occurs? It seems like there may be something else causing side effects in your code.

Just to be clear, the error about the slice index being out of bounds is saying that the paramName is not as long as expected. This would definitely be a bug in Revel's binder code. 

The issue is that we need to be able to reproduce the bug on our side so we can fix it with some level of confidence.

We're very interested in figuring out what caused this error for you. Please let us know!

**Comment by brendensoares** [comment]
PS - I've tried post and get methods of submitting the form and setting the checkbox to on and off with the same successful result. I tried on both Revel v0.17.1 and v0.18.0.

Here's my code:
`controllers/app.go`:
```
[...]
func (c App) Index() revel.Result {
	return c.Render()
}

func (c App) Post() revel.Result {
	var invisible map[string]string
	c.Params.Bind(&invisible, "invisible")

	return c.RenderJSON(invisible)
}
```

`views/App/Index.html`:
```
[...]
<form action="/post" method="post">
	<input name="invisible[32ffb9e6-92d2-11e7-b1bf-54a050de5eca]" value="on" type="checkbox">
	<input type="submit">
</form>
[...]
```

`app/routes`:
```
GET     /     App.Index
POST    /post App.Post
```

**Comment by acegishniz** [comment]
I have tested on a sample code, and the problem is not solved.

Here's my code:
`controllers/app.go:`

```
[...]
type App struct {
	*revel.Controller
}

func (c App) Index() revel.Result {
	return c.Render()
}


func (c App) IndexPost() revel.Result {

	var invisible map[string]string
	c.Params.Bind(&invisible, "invisible")
	return c.Redirect(routes.App.Index())
}
```

`views/App/Index.html:`
```
[...]
        <form role="form" action="{{url `App.IndexPost`}}" method="POST">

            <table>
                <thead>
                <tr>
                    <th> invisible</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <input name="invisible[46a9cb32-7081-11e7-83e4-663263313934]"
                               value="on" type="checkbox">
                    </td>
                </tr>
                </tbody>
            </table>
            <button type="submit" name="submit"> Submit</button>

        </form>
[...]
```

`app/routes:`

```
GET     /                     App.Index
POST    /                     App.IndexPost
```

And `revel version` command output on terminal:

```
DEBUG 12:58:16  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 12:58:16  revel template_engine.go:45: Registered template engine loaded         section=template go=nil LOG15_ERROR="Normalized odd number of arguments by adding nil" 
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.19.0 (2018-02-06)
   go1.7.4 linux/amd64

```

and the panic:

```
INFO  13:00:42    app server.go:2317: http: panic serving 127.0.0.1:60988: runtime error: slice bounds out of range
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc42036cc00)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x83d660, 0xc420010180)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/revel/revel.InterceptorFilter.func1(0xc42022b040)
	/home/acegishniz/gowork/src/github.com/revel/revel/intercept.go:98 +0x7d
panic(0x83d660, 0xc420010180)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/revel/revel.bindMap(0xc420309860, 0x8b923d, 0x9, 0xac1e40, 0x83b820, 0x16, 0x806f40, 0xc4202f8390)
	/home/acegishniz/gowork/src/github.com/revel/revel/binder.go:437 +0x50f
github.com/revel/revel.Bind(0xc420309860, 0x8b923d, 0x9, 0xac1e40, 0x83b820, 0x195, 0x0, 0xc420030800)
	/home/acegishniz/gowork/src/github.com/revel/revel/binder.go:464 +0x7d
github.com/revel/revel.(*Params).Bind(0xc420309860, 0x806f40, 0xc4202f8390, 0x8b923d, 0x9)
	/home/acegishniz/gowork/src/github.com/revel/revel/params.go:100 +0x161
github.com/acegishniz/my-app/app/controllers.App.IndexPost(0xc42022b040, 0xc4202f4b20, 0xc420126bc8)
	/home/acegishniz/gowork/src/github.com/acegishniz/my-app/app/controllers/app.go:20 +0x78
github.com/acegishniz/my-app/app/controllers.(*App).IndexPost(0xc42002f248, 0x0, 0x0)
	<autogenerated>:29 +0x52
reflect.Value.call(0x8a5540, 0xc42002f248, 0x1213, 0x8b442e, 0x4, 0x0, 0x0, 0x0, 0xc4202f8370, 0x13, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x8a5540, 0xc42002f248, 0x1213, 0x0, 0x0, 0x0, 0xc42002f248, 0x1213, 0xab7ca0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/revel/revel.ActionInvoker(0xc42022b040, 0xc42037ead8, 0x0, 0x0)
	/home/acegishniz/gowork/src/github.com/revel/revel/invoker.go:45 +0x632
github.com/revel/revel.CompressFilter(0xc42022b040, 0xc42037ead8, 0x1, 0x1)
	/home/acegishniz/gowork/src/github.com/revel/revel/compress.go:84 +0x9e
github.com/revel/revel.InterceptorFilter(0xc42022b040, 0xc42037ead0, 0x2, 0x2)
	/home/acegishniz/gowork/src/github.com/revel/revel/intercept.go:108 +0xee
github.com/acegishniz/my-app/app.glob..func1(0xc42022b040, 0xc42037eac8, 0x3, 0x3)
	/home/acegishniz/gowork/src/github.com/acegishniz/my-app/app/init.go:49 +0x18e
github.com/revel/revel.I18nFilter(0xc42022b040, 0xc42037eac0, 0x4, 0x4)
	/home/acegishniz/gowork/src/github.com/revel/revel/i18n.go:212 +0x2ff
github.com/revel/revel.ValidationFilter(0xc42022b040, 0xc42037eab8, 0x5, 0x5)
	/home/acegishniz/gowork/src/github.com/revel/revel/validation.go:269 +0x1b5
github.com/revel/revel.FlashFilter(0xc42022b040, 0xc42037eab0, 0x6, 0x6)
	/home/acegishniz/gowork/src/github.com/revel/revel/flash.go:50 +0x138
github.com/revel/revel.SessionFilter(0xc42022b040, 0xc42037eaa8, 0x7, 0x7)
	/home/acegishniz/gowork/src/github.com/revel/revel/session.go:158 +0x126
github.com/revel/revel.ParamsFilter(0xc42022b040, 0xc42037eaa0, 0x8, 0x8)
	/home/acegishniz/gowork/src/github.com/revel/revel/params.go:179 +0xb2
github.com/revel/revel.FilterConfiguringFilter(0xc42022b040, 0xc42037ea98, 0x9, 0x9)
	/home/acegishniz/gowork/src/github.com/revel/revel/filterconfig.go:211 +0x128
github.com/revel/revel.RouterFilter(0xc42022b040, 0xc42037ea90, 0xa, 0xa)
	/home/acegishniz/gowork/src/github.com/revel/revel/router.go:790 +0x2cc
github.com/revel/revel.glob..func32(0xc42022b040, 0xc42037ea88, 0xb, 0xb)
	/home/acegishniz/gowork/src/github.com/revel/revel/watcher.go:222 +0x7a
github.com/revel/revel.handleInternal(0xab9920, 0xc4202478c0)
	/home/acegishniz/gowork/src/github.com/revel/revel/server-engine.go:145 +0x4d8
github.com/revel/revel.(*GoHttpServer).Handle(0xc420229fb0, 0xabc6e0, 0xc42035e5b0, 0xc42037ca50)
	/home/acegishniz/gowork/src/github.com/revel/revel/server_adapter_go.go:101 +0x2ef
github.com/revel/revel.(*GoHttpServer).Init.func3(0xabc6e0, 0xc42035e5b0, 0xc42037ca50)
	/home/acegishniz/gowork/src/github.com/revel/revel/server_adapter_go.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42023a9b0, 0xabc6e0, 0xc42035e5b0, 0xc42037ca50)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420235280, 0xabc6e0, 0xc42035e5b0, 0xc42037ca50)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42036cc00, 0xabcfa0, 0xc420367800)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d  section=system 
INFO  13:00:42    app reverseproxy.go:279: http: proxy error: EOF                    section=system 

```

**Comment by acegishniz** [comment]
`Here is the screenshot of error:`

![screenshot from 2018-02-12 10-32-21](https://user-images.githubusercontent.com/10413534/36086198-0eaba742-0fe0-11e8-8e12-0537708a8c1f.png)

**Comment by hwsoderlund** [comment]
PR #1344 has been merged to master. I guess this should be closed now.
