### ISSUE TITLE
"Runtime error: Invalid memory address" when starting app

### ISSUE THREAD

**Issue by lezorich** [revel/revel#1286]
I'm currently working with revel 0.18.0 and golang 1.9. Everything was working fine, but now when I try to start the app with `revel run` I started to get this exception:

```
DEBUG 17:54:15  revel harness.go:146: Rebuild Called                            
INFO  17:54:15  revel  build.go:235: Cleaning dir tmp                          
INFO  17:54:15  revel  build.go:235: Cleaning dir routes                       
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x749e41]

goroutine 1 [running]:
main.main.func2()
        /home/administrador/go/src/github.com/revel/cmd/revel/rev.go:86 +0x6b
panic(0x882440, 0xb88a50)                                                                                                                                        
        /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
go/ast.Walk(0xb56320, 0xc420527e80, 0xb57f20, 0x0)
        /usr/lib/go-1.9/src/go/ast/walk.go:224 +0x1b51
go/ast.Inspect(0xb57f20, 0x0, 0xc420527e80)
        /usr/lib/go-1.9/src/go/ast/walk.go:385 +0x4b
github.com/revel/cmd/harness.getValidationKeys(0xc4202aa5c0, 0xc42041f170, 0xc4203ce510, 0xc420397ce0)
        /home/administrador/go/src/github.com/revel/cmd/harness/reflect.go:550 +0xed
github.com/revel/cmd/harness.processPackage(0xc4202aa5c0, 0xc4203b8dc0, 0x44, 0xc420397ce0, 0x5f, 0xc420452870, 0x0)
        /home/administrador/go/src/github.com/revel/cmd/harness/reflect.go:245 +0x352
github.com/revel/cmd/harness.ProcessSource.func1(0xc420397ce0, 0x5f, 0xb5e3a0, 0xc420454dd0, 0x0, 0x0, 0x0, 0x0)
        /home/administrador/go/src/github.com/revel/cmd/harness/reflect.go:185 +0x524
github.com/revel/revel.fsWalk.func1(0xc420397ce0, 0x5f, 0xb5e3a0, 0xc420454dd0, 0x0, 0x0, 0x0, 0x0)
        /home/administrador/go/src/github.com/revel/revel/util.go:272 +0x1bf
path/filepath.walk(0xc420397c20, 0x5f, 0xb5e3a0, 0xc420454dd0, 0xc420354420, 0x0, 0x0)
        /usr/lib/go-1.9/src/path/filepath/path.go:356 +0x81
path/filepath.walk(0xc420397800, 0x59, 0xb5e3a0, 0xc4204548f0, 0xc420354420, 0x0, 0x0)
        /usr/lib/go-1.9/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc4203b8d20, 0x50, 0xb5e3a0, 0xc420454680, 0xc420354420, 0x0, 0x0)
        /usr/lib/go-1.9/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc4202e5a40, 0x46, 0xb5e3a0, 0xc420525040, 0xc420354420, 0x0, 0x0)
        /usr/lib/go-1.9/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc4203a2880, 0x3b, 0xb5e3a0, 0xc420170000, 0xc420354420, 0x0, 0x0)
        /usr/lib/go-1.9/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc42001b040, 0x34, 0xb5e3a0, 0xc4203afd40, 0xc420354420, 0x0, 0x30)
        /usr/lib/go-1.9/src/path/filepath/path.go:381 +0x3a0
path/filepath.Walk(0xc42001b040, 0x34, 0xc420354420, 0xc420038a80, 0x7f96aba996c8)
        /usr/lib/go-1.9/src/path/filepath/path.go:403 +0x11d
github.com/revel/revel.fsWalk(0xc42001b040, 0x34, 0xc42001b040, 0x34, 0xc4203543f0, 0xc420195601, 0xc4203543f0)
        /home/administrador/go/src/github.com/revel/revel/util.go:274 +0xa9
github.com/revel/revel.Walk(0xc42001b040, 0x34, 0xc4203543f0, 0x19, 0xb1)
        /home/administrador/go/src/github.com/revel/revel/util.go:222 +0x49
github.com/revel/cmd/harness.ProcessSource(0xc4200110c0, 0x4, 0x4, 0xc42002b370, 0xc42002b300)
        /home/administrador/go/src/github.com/revel/cmd/harness/reflect.go:106 +0x2b8
github.com/revel/cmd/harness.Build(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/administrador/go/src/github.com/revel/cmd/harness/build.go:35 +0xe5
github.com/revel/cmd/harness.(*Harness).Refresh(0xc4202cacc0, 0x0)
        /home/administrador/go/src/github.com/revel/cmd/harness/harness.go:147 +0xe2
github.com/revel/revel.(*Watcher).Notify(0xc4202c6910, 0x0)
        /home/administrador/go/src/github.com/revel/revel/watcher.go:178 +0x274
github.com/revel/cmd/harness.(*Harness).Run(0xc4202cacc0)
        /home/administrador/go/src/github.com/revel/cmd/harness/harness.go:186 +0x190
main.runApp(0xc4200100e0, 0x2, 0x2)
        /home/administrador/go/src/github.com/revel/cmd/revel/run.go:131 +0x47b
main.main()
        /home/administrador/go/src/github.com/revel/cmd/revel/rev.go:94 +0x3c9
```

What can be going on?

**Comment by notzippy** [comment]
This issue was moved to revel/cmd#113
