### ISSUE TITLE
windows10 , revel crash on Redirect() method

### ISSUE THREAD

**Issue by SamueleCat** [revel/revel#1305]
revel version
```
[36mDEBUG[0m 21:38:17  revel  server.go:27: RegisterServerEngine: Registered engine   [36msection[0m=server [36mname[0m=go
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.18.0 (2017-10-30)
   go1.9.2 windows/amd64
```

following the tutorial up to the page:
http://revel.github.io/tutorial/firstapp.html

file \conf\routes :
```
module:testrunner
# module:jobs

GET     /                                       App.Index

# Ignore favicon requests
GET     /favicon.ico                            404

# Map static resources from the /app/public folder to the /public path
GET     /public/*filepath                       Static.Serve("public")

GET     /App/Hello                               App.Hello
```

file \app\controllers\app.go :
```
package controllers

import (
	"github.com/revel/revel"
)

type App struct {
	*revel.Controller
}

func (c App) Index() revel.Result {
	greeting := "test"
	return c.Render(greeting)
}

func (c App) Hello(myName string) revel.Result {
	c.Validation.Required(myName).Message("Your name is required!")
	c.Validation.MinSize(myName, 3).Message("Your name is not long enough!")

	if c.Validation.HasErrors() {
		c.Validation.Keep()
		c.FlashParams()
		return c.Redirect(App.Index)
	}

	return c.Render(myName)
}
```

ERROR on submit empty name or reloading the page:
http://localhost:9000/App/Hello?myName=

```
INFO  21:28:30    app   plugin.go:9: Go to /@tests to run the tests.
Listening on.. localhost:52142
[32mINFO [0m 21:28:30  revel harness.go:190: Listening on :9000
Returned  0x0
INFO  21:28:39    app server.go:2848: http: panic serving 127.0.0.1:52145: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc0423c20a0)
        C:/Go/src/net/http/server.go:1697 +0xd7
panic(0x8807e0, 0xb7b450)
        C:/Go/src/runtime/panic.go:491 +0x291
github.com/revel/revel.(*Module).Namespace(...)
        C:/Users/Samuele/go_language/src/github.com/revel/revel/module.go:60
github.com/revel/revel.getRedirectURL(0x869080, 0x925100, 0x0, 0x0, 0x0, 0xb, 0xc042437b38, 0x7ea784, 0xc0422136c0)
        C:/Users/Samuele/go_language/src/github.com/revel/revel/results.go:472 +0x278
github.com/revel/revel.(*RedirectToActionResult).Apply(0xc04234f470, 0xc042128fc0, 0xc0420a1270)
        C:/Users/Samuele/go_language/src/github.com/revel/revel/results.go:439 +0x5d
github.com/revel/revel.handleInternal(0xb4a8a0, 0xc042256000)
        C:/Users/Samuele/go_language/src/github.com/revel/revel/server-engine.go:147 +0x7f6
github.com/revel/revel.(*GoHttpServer).Handle(0xc0421f3e30, 0xb4daa0, 0xc04223a380, 0xc0421d9700)
        C:/Users/Samuele/go_language/src/github.com/revel/revel/server_adapter_go.go:101 +0x3a5
github.com/revel/revel.(*GoHttpServer).Init.func3(0xb4daa0, 0xc04223a380, 0xc0421d9700)
        C:/Users/Samuele/go_language/src/github.com/revel/revel/server_adapter_go.go:43 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc04224a9c0, 0xb4daa0, 0xc04223a380, 0xc0421d9700)
        C:/Go/src/net/http/server.go:1918 +0x4b
net/http.serverHandler.ServeHTTP(0xc042212ea0, 0xb4daa0, 0xc04223a380, 0xc0421d9700)
        C:/Go/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc0423c20a0, 0xb4e2a0, 0xc04231fe80)
        C:/Go/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2720 +0x28f section=system
[32mINFO [0m 21:28:39    app reverseproxy.go:324: http: proxy error: EOF                    [32msection[0m=system
```

but, if I change the line :
`return c.Redirect(App.Index)`
in
`return c.Redirect("/")`
it doesn't panic anymore and works as expected.

*also notice the escape shell characters

**Comment by SamueleCat** [comment]
I've tested the same code under Linux Ubuntu Server 14.04, go 1.9.2, revel 0.18.0  => no issues.

**Comment by runner-mei** [comment]
return c.Redirect(App.Index)  
to
return c.Redirect(routes.App.Index())

**Comment by SamueleCat** [comment]
Update: I've updated Go to the latest version 1.9.3 and the problem disappear. I can't tell if 1.9.3 has a fix or it was windows related.
*I still see the escape characters:
`[36mDEBUG [0m`
regardless if log.colorize is set to true or false (it is present in every section of app.conf)

**Comment by notzippy** [comment]
I cannot repeat this, closing...

**Comment by lujiacn** [comment]
I have the same issue before:
When using format below, will trigger the return 0x0 issue.
```
return c.Redirect(Controller.Action)
```
have to update to format below to avoid the issue
```
return c.Redirect(routes.Controller.Action())
```
The safe way is pass url string to Redirect().

**Comment by lokhman** [comment]
> I still see the escape characters: `[36mDEBUG [0m` regardless if `log.colorize` is set to `true` or `false` (it is present in every section of app.conf)

+1 I have the same issue on Windows
