### ISSUE TITLE
Auto-interceptor BeforeAfterFilter fails to compile

### ISSUE THREAD

**Issue by intel352** [revel/revel#1336]
I've built a more complex controller, which implemented the BeforeAfterFilter's `Before` method to enable the auto-interceptor functionality. After encountering this error, I stripped down to the simple example shown below, and still receive the same error.

I'm satisfying the signature requires for the `Before` method, so I'm not sure why this is panicking. 

The goal here is to have a method that can run logic before the controller actions execute, to set up some variables within the controller. This is why I'm using the auto-interceptor approach rather than the `init()...InterceptorFunc()` approach (I know the controller instance could be fetched, but the docs say to use interceptor when that pattern is needed).

tagging @notzippy as I know he originated this functionality.

Go version:
`go version go1.10.1 darwin/amd64`

Filters config:
```
	revel.Filters = []revel.Filter{
		revel.PanicFilter,             // Recover from panics and display an error page instead.
		revel.RouterFilter,            // Use the routing table to select the right Action
		revel.FilterConfiguringFilter, // A hook for adding or removing per-Action filters.
		revel.ParamsFilter,            // Parse parameters into Controller.Params.
		revel.SessionFilter,           // Restore and write the session cookie.
		revel.FlashFilter,             // Restore and write the flash cookie.
		revel.ValidationFilter,        // Restore kept validation errors and save new ones from cookie.
		revel.I18nFilter,              // Resolve the requested language
		HeaderFilter,                  // Add some security based headers
		revel.InterceptorFilter,       // Run interceptors around the action.
		revel.CompressFilter,          // Compress the result.
		revel.BeforeAfterFilter,	   // Before/After filters
		revel.ActionInvoker,           // Invoke the action.
	}
```

Basic App controller:
```
package controllers

import (
	"github.com/revel/revel"
)

type App struct {
	*revel.Controller
}

func (c App) Before() (r revel.Result, o App) {
	return
}

func (c App) Index() revel.Result {
	return c.Render()
}
```

Output when running web app:
```
INFO  13:39:33    app    main.go:30: Running revel server                      
panic: reflect: Elem of invalid type

goroutine 1 [running]:
reflect.(*rtype).Elem(0x150dde0, 0x19, 0x150dde0)
	/usr/local/Cellar/go/1.10.1/libexec/src/reflect/type.go:958 +0x143
github.com/revel/revel.(*ControllerTypeEvents).check.func1(0x1587300, 0x150dde0)
	/Users/jlangevin/go/src/github.com/revel/revel/controller_type.go:111 +0xa1e
github.com/revel/revel.(*ControllerTypeEvents).check(0xc4200ccea0, 0x1587300, 0x150dde0, 0x17f9cd8, 0x0, 0x0)
	/Users/jlangevin/go/src/github.com/revel/revel/controller_type.go:129 +0xcc
github.com/revel/revel.NewControllerTypeEvents(0xc4200cce40, 0xc4200cce40)
	/Users/jlangevin/go/src/github.com/revel/revel/controller_type.go:93 +0x96
github.com/revel/revel.AddControllerType(0x17d2280, 0x1587300, 0x150dde0, 0xc4200c0108, 0x1, 0x1, 0x1012558)
	/Users/jlangevin/go/src/github.com/revel/revel/controller_type.go:49 +0x152
github.com/revel/revel.RegisterController(0x150b180, 0x0, 0xc4200c0108, 0x1, 0x1)
	/Users/jlangevin/go/src/github.com/revel/revel/controller.go:533 +0x1f8
main.main()
	/Users/jlangevin/go/src/github.com/intel352/myapp/app/tmp/main.go:32 +0x224
INFO  13:39:33  revel harness.go:190: Listening on :9000
```

Relevant section in main.go (~line 32)
```
	revel.RegisterController((*controllers.App)(nil),
		[]*revel.MethodType{
			&revel.MethodType{
				Name: "Index",
				Args: []*revel.MethodArg{ 
				},
				RenderArgNames: map[int][]string{ 
					16: []string{ 
					},
				},
			},
			
		})
```

**Comment by intel352** [comment]
@notzippy After making the change in the associated PR, the scenario provided above now functions. Please make any adjustments necessary.

**Comment by notzippy** [comment]
Thanks, will follow with a master release soon
