### ISSUE TITLE
Revel Package "myapp"

### ISSUE THREAD

**Issue by shanshel** [revel/revel#1342]
Hello. I'm facing an issue

`revel package myapp`

work as expected and give me the .tar files
but however when i try to run it
it fails to load, and I get this message 

```

DEBUG 12:49:25  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go
DEBUG 12:49:25  revel template_engine.go:45: Registered template engine loaded         section=template go=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
CRIT  12:49:25  revel  revel.go:269: Failed to import  with error:             error="import \"\": invalid import path" 
panic: Failed to import  with error:

goroutine 1 [running]:
github.com/revel/revel/logger.(*RevelLogger).Panic(0xc042068da0, 0xc0420738c0, 0x1d, 0xc042107d60, 0x2, 0x2)
        C:/Users/user/go/src/github.com/revel/revel/logger/logger.go:149 +0xb6
github.com/revel/revel.findSrcPaths(0x0, 0x0, 0x9cd15e, 0x1, 0x0, 0x0)
        C:/Users/user/go/src/github.com/revel/revel/revel.go:269 +0x244
github.com/revel/revel.Init(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/user/go/src/github.com/revel/revel/revel.go:123 +0x11f
main.main()
        C:/Users/user/go/src/RevelPOS/app/tmp/main.go:35 +0x8a
```

do you have any idea ?

**Comment by shanshel** [comment]
I fix it

this command not working for me "Windows 10"
`
@echo off
Myapp.exe -importPath RevelPOS -srcPath %CD%\src -runMode dev
`


I just removed %CD% and it works

`
RevelPOS.exe -importPath RevelPOS -srcPath src -runMode dev
`

**Comment by hinet** [comment]
I have the same problem. I suggest fixing bugs in Windows 10.

**Comment by notzippy** [comment]
Im reopening this so it can be tracked
