### ISSUE TITLE
panic: reflect.Set: value of type string is not assignable to type *string

### ISSUE THREAD

**Issue by xaionaro** [revel/revel#1346]
```
panic: reflect.Set: value of type string is not assignable to type *string

goroutine 2195089 [running]:
reflect.Value.assignTo(0x1843560, 0xc4c1c571e0, 0x98, 0x1aba604, 0xb, 0x181e800, 0x0, 0x1843560, 0xc4c1c571e0, 0x98)
        /usr/lib/go-1.10/src/reflect/value.go:2235 +0x427
reflect.Value.Set(0x181e800, 0xc4c6c77738, 0x196, 0x1843560, 0xc4c1c571e0, 0x98)
        /usr/lib/go-1.10/src/reflect/value.go:1373 +0xa4
github.com/revel/revel.bindStruct(0xc4ead07560, 0x1ab957b, 0xa, 0x1d52880, 0x1a86720, 0x18e3c20, 0x1a86720, 0x0)
        ***/src/github.com/revel/revel/binder.go:330 +0x3ba
github.com/revel/revel.Bind(0xc4ead07560, 0x1ab957b, 0xa, 0x1d52880, 0x1a86720, 0x19f9720, 0xc49470ea30, 0x1613)
        ***/src/github.com/revel/revel/binder.go:464 +0x7d
github.com/revel/revel.ActionInvoker(0xc4bd4c1f08, 0xc420e6b098, 0x0, 0x1)
        ***/src/github.com/revel/revel/invoker.go:29 +0x2db
voip/app.glob..func1.1(0xc420e6b098, 0x0, 0x1, 0xc5015151a0, 0x17d3861, 0xb, 0xc4209d3140, 0x1aa402d, 0x4, 0xc4211416d0, ...)
        ***/app/init.go:2533 +0x10c
created by voip/app.glob..func1
        ***/app/init.go:2525 +0x4182
```

Line `init.go:2533`:
```
revel.ActionInvoker(&controller, f)
```
(`controller` is a `revel.Controller`)

```
$ go version
go version go1.10.1 linux/amd64
```

```
$ revel version
DEBUG 16:23:18  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 16:23:18  revel template_engine.go:45: Registered template engine loaded         section=template go=nil LOG15_ERROR="Normalized odd number of arguments by adding nil" 
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.19.0 (2018-02-06)
   go1.10.1 linux/amd64
```

**Comment by notzippy** [comment]
Do you know what target it is binding to ?

**Comment by xaionaro** [comment]
No. I even don't know on which Controller.Action this going on.

**Comment by notzippy** [comment]
It looks like you are attempting to bind a string to a string pointer that is in the controller. You do not need to define your controller variables as pointers. Closing

**Comment by xaionaro** [comment]
@notzippy where do I do that? There's no debugging information to understand where is the error.

**Comment by notzippy** [comment]
@xaionaro Do you have any controllers that have functions defined like the following ? 
```
func (f *MyController) Input(apple *string) {

}
```
Im going to reopen this because you are right it should be better logged when the error occurs

**Comment by xaionaro** [comment]
@notzippy well. I don't see such:
```
controllers$ grep -RIn revel.Result . | grep --color string | grep '*'
./phones.go:155:func (c *Phones) ShowConfigFanvil(mac string) revel.Result {
./app.go:529:func (c App) ChatMessageSentJson( /*token string, channelId string, userName string, text string*/ ) revel.Result {
```

I could check every `Action` manually:
```
controllers$ grep -RIn revel.Result . | wc -l
260
```
But this can take too much time.

I believe I use binding to a structure (with `*string`) somewhere. But I don't see where it could be. IMO, `revel` should report something about which line actually caused the panic.

**Comment by notzippy** [comment]
Agreed, Revel cant point the line but it should be able to report the
controller.function - I can look at the source code this weekend and let
you know what changes would need to be made to make this easier for you to
look for.
