### ISSUE TITLE
Nothing works after upgrade

### ISSUE THREAD

**Issue by daxorid** [revel/revel#1361]
After a recent upgrade via go get -u, revel appears to be broken. Following is the log:

[root@foobarapp ~]# revel run foobarapp
DEBUG 20:59:59  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 20:59:59  revel template_engine.go:45: Registered template engine loaded         section=template go=nil LOG15_ERROR="Normalized odd number of arguments by adding nil" 
~
~ revel! http://revel.github.io
~
WARN  20:59:59  revel     run.go:94: Unable to run using an import path, assuming import path is working directory %s %s  Argument=foobarapp error="cannot find package \"foobarapp\" in any of:\n\t/usr/lib/golang/src/foobarapp (from $GOROOT)\n\t/root/go/src/foobarapp (from $GOPATH)" 
Trying to build with foobarapp (0xb464e0,0xc4201ee450)
CRIT  20:59:59  revel  revel.go:269: Failed to import ../.. with error:        error="import \"../..\": import relative to unknown directory" 
panic: Failed to import ../.. with error: [recovered]
	panic: Failed to import ../.. with error:

goroutine 1 [running]:
main.main.func2()
	/root/go/src/github.com/revel/cmd/revel/rev.go:86 +0x6b
panic(0x8544c0, 0xc4201ee600)
	/usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/revel/revel/logger.(*RevelLogger).Panic(0xc420042d40, 0xc420020390, 0x22, 0xc4200cf680, 0x2, 0x2)
	/root/go/src/github.com/revel/revel/logger/logger.go:149 +0xaf
github.com/revel/revel.findSrcPaths(0xc420017aa0, 0x5, 0x8ff5e6, 0x1, 0xc420017aa0, 0x5)
	/root/go/src/github.com/revel/revel/revel.go:269 +0x247
github.com/revel/revel.Init(0x7ffc62237729, 0x9, 0xc420017aa0, 0x5, 0x0, 0x0)
	/root/go/src/github.com/revel/revel/revel.go:123 +0x118
main.runApp(0xc4200100b0, 0x1, 0x1)
	/root/go/src/github.com/revel/cmd/revel/run.go:116 +0x8c
main.main()
	/root/go/src/github.com/revel/cmd/revel/rev.go:94 +0x3c9

**Comment by daxorid** [comment]
Quick followup, the only thing google yields on this issue is a gist, but it doesn't appear to be linked to an actual issue:

https://gist.github.com/zs14/1aa71de47986ba4056998ad3f5765717
