### ISSUE TITLE
Revel cmd not working

### ISSUE THREAD

**Issue by amitsharma8891** [revel/revel#1374]
Hi,

From last 3 days I tried to install revel on mac but unfortunately I couldn't.
Here is details of my dev setup error

```export GOROOT=/usr/local/go
export GOPATH=$HOME/go
#export PATH=$HOME/go/bin:$PATH
export PATH=$PATH:$GOROOT/bin```


when I run `revel version`:
```INFO  10:21:20 command_config.go:120: Checking import path /Users/amitsharma/go with /Users/amitsharma/go
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc4200981c0, 0x14)
	/Users/amitsharma/go/src/github.com/revel/cmd/model/command_config.go:122 +0x907
main.main()
	/Users/amitsharma/go/src/github.com/revel/cmd/revel/revel.go:133 +0x243
```

when I run `revel new my-app -v`
```INFO  10:27:22 command_config.go:136: Returned import path                     path=sample1 buildpath=/Users/amitsharma/go
Revel executing: create a skeleton Revel application
INFO  10:27:22   file.go:272: error opening directory: open /Users/amitsharma/go/src/sample1: no such file or directory
Exec: [/usr/local/go/bin/go get -d -v]
CRIT  10:27:22    new.go:201: Abort: Could not find or 'go get' Skeleton  source code: can't load package: package .: no Go files in /Users/amitsharma/go```


I please let me know where am I doing wrong?

Thanks
Amit

**Comment by amitsharma8891** [comment]
I think no one is interested in solving this issue.

**Comment by gourlaa** [comment]
We have the same problem

**Comment by notzippy** [comment]
This has been merged, let us know if the issue persists.

**Comment by amitsharma8891** [comment]
Oh, It's working now, thanks a lot.

**Comment by amitsharma8891** [comment]
> This has been merged, let us know if the issue persists.

After the fix, now it's working. 
Thanks
