### ISSUE TITLE
Quick Start chat example causes invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by prewk** [revel/revel#1419]
Hi, I'm new to Go and trying out the Quick Start on [your landing page](https://revel.github.io/). I have a working, new, Go installation (`go1.11.5 darwin/amd64`) with `$GOPATH` (`/Users/oskar/src/go`) etc.

Following your steps:

```sh
# get 'revel' framework and command
go get github.com/revel/cmd/revel

# Get the example apps
git clone https://github.com/revel/examples \
$GOPATH/src/github.com/revel/examples

# revel the chat app
revel run github.com/revel/examples/chat
```

The last command yields:

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x123350e]

goroutine 1 [running]:
github.com/revel/cmd/utils.FindSrcPaths(0x7ffeefbffb32, 0x1e, 0x14ddc50, 0x16, 0x0, 0x0, 0x0, 0x1416520, 0xc0000abf30, 0xc0000d5c68, ...)
    /Users/oskar/src/go/src/github.com/revel/cmd/utils/file.go:358 +0x4fe
github.com/revel/cmd/model.(*CommandConfig).SetVersions(0xc0000ac1e0, 0x14dc86c, 0x14)
    /Users/oskar/src/go/src/github.com/revel/cmd/model/command_config.go:301 +0xc0
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc0000ac1e0, 0x17, 0x2)
    /Users/oskar/src/go/src/github.com/revel/cmd/model/command_config.go:154 +0x68e
main.main()
    /Users/oskar/src/go/src/github.com/revel/cmd/revel/revel.go:94 +0x161
```

**Comment by dmjones** [comment]
I also had this issue, but it was fixed when I updated my revel command with:

```
go get -u github.com/revel/cmd
```

**Comment by notzippy** [comment]
Yes this sounds like a versioning issue, what is the output of `revel version` ?

**Comment by prewk** [comment]
Tried again, it works suddenly (without attempting to manually updating anything). Output of `revel version`:

```
Revel executing: displays the Revel Framework and Go version
Revel Framework	:	0.21.0	(0.21.0 remote master branch)
Revel Cmd	:	0.21.1	(0.21.1 remote master branch)
Revel Modules	:	0.21.0	(0.21.0 remote master branch)

go version go1.11.5 darwin/amd64
```

🤷‍♂️

**Comment by digininja** [comment]
I've just had this problem as well, it was all broken till I ran `revel version` and then it started working. I assume running that sets something up that was initially missing.

**Comment by digininja** [comment]
I had exactly the same experience today on a second box. Got errors, not
the same as reported here, then ran the version command and after that it
all started working.

**Comment by rpagliuca** [comment]
Thanks @digininja, running `revel version` fixed the installation.

**Comment by chamarts** [comment]
strange, works for me too !
