### ISSUE TITLE
Problem working out version

### ISSUE THREAD

**Issue by digininja** [revel/revel#1438]
When I try to get the version on two boxes I get the following:

```
$ revel version
revel executing: displays the Revel Framework and Go version
WARN  21:51:10 version.go:71: Unable to extract version information from Revel library error,err=nil LOG15_ERROR="Normalized odd number of arguments by adding nil" 
Revel Framework :       Unknown (0.21.0 remote master branch)
Revel Cmd       :       0.21.1  (0.21.1 remote master branch)
Revel Modules   :       Unknown (0.21.0 remote master branch)

go version go1.12.3 linux/amd64
```
revel then refuses to start any existing apps. I can create and run a new app but the existing one I'm trying to deploy fails with this error which is also about versions.

```
revel  run -a /home/authlab/go/src/github.com/digininja/authlab/authlabweb/
CRIT  21:51:22 command_config.go:155: Failed to fetch revel versions           error="Failed to import rc/github.com/digininja/authlab/authlabweb with error cannot find package \"rc/github.com/digininja/authlab/authlabweb\" in any of:\n\t/opt/go/src/rc/github.com/digininja/authlab/authlabweb (from $GOROOT)\n\t/home/authlab/go/src/rc/github.com/digininja/authlab/authlabweb (from $GOPATH)" 
panic: Failed to fetch revel versions

goroutine 1 [running]:
github.com/revel/cmd/logger.(*RevelLogger).Panic(0xc00005c6e0, 0x92b402, 0x1e, 0xc00000f1a0, 0x2, 0x2)
        /home/authlab/go/src/github.com/revel/cmd/logger/revel_logger.go:66 +0x9b
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc00000c1e0, 0x3c, 0x2)
        /home/authlab/go/src/github.com/revel/cmd/model/command_config.go:155 +0x74e
main.main()
        /home/authlab/go/src/github.com/revel/cmd/revel/revel.go:94 +0x161
```

Looking at the error, there is an extra rc in this path:

```
/home/authlab/go/src/rc/github.com/digininja/authlab/authlabweb
```

It isn't coming from either of my environment variables:

```
$ echo $GOROOT 
/opt/go/
$ echo $GOPATH
/home/authlab/go/
```

And the code works fine on the dev box.

**Comment by digininja** [comment]
My mistake, I'd managed to get a version of Go installed by the system in the path before my custom installed one so it was picking up the old binary but the new stuff through $GOROOT.

**Comment by myk4040okothogodo** [comment]
@digininja what was your exact solution ?

**Comment by digininja** [comment]
Uninstall every version of Go except the one you want to use.
