### ISSUE TITLE
revel installs to $GOPATH/pkg instead of $GOPATH/src

### ISSUE THREAD

**Issue by yulivee** [revel/revel#1472]
When trying to install revel according to documentation, it installs to $GOPATH/pkg I stead of $GOPATH/src. This messes up the revel Fullpath and I cannot start my application, because it cannot find the revel cmd. This only happens on our centos production box, it correctly installs on my windows dev machine and my Ubuntu WSL.
Error:
```
revel run -v -a aces-tokenplatform
INFO  07:01:08   revel.go:94: Returned import path                     buildpath=/root/go  path=aces-tokenplatform
INFO  07:01:08 command_config.go:301: Seeking app package                      app=aces-tokenplatform
INFO  07:01:08 command_config.go:301: Seeking remote package                   using=aces-tokenplatform remote=github.com/revel/revel
INFO  07:01:08 command_config.go:301: Resolved called Seeking remote package   using=aces-tokenplatform remote=github.com/revel/revel
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63f9c1]

goroutine 1 [running]:
github.com/revel/cmd/utils.FindSrcPaths(0x7ffdb03f8666, 0x12, 0x926b9f, 0x16, 0x0, 0xc0000c2cf0, 0x0, 0x0, 0x4, 0x4, ...)
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/utils/file.go:358 +0x481
github.com/revel/cmd/model.(*CommandConfig).SetVersions(0xc00000c1e0, 0x925702, 0x14)
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/model/command_config.go:301 +0xcb
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc00000c1e0, 0x1f, 0x2)
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/model/command_config.go:154 +0x685
main.main()
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/revel/revel.go:94 +0x161
```

```
go version
go version go1.12.9 linux/amd64

 go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build343991327=/tmp/go-build -gno-record-gcc-switches"

cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

after `go get github.com/revel/revel` and `go get github.com/revel/cmd/revel`
```
$/root/go/> tree -L 4
.
.
|-- bin
|   `-- revel
|-- pkg
|   `-- mod
|       |-- cache
|       |   |-- download
|       |   `-- vcs
|       |-- github.com
|       |   |-- inconshreveable
|       |   |-- mattn
|       |   |-- revel
|       |   |-- twinj
|       |   `-- xeonx
|       |-- golang.org
|       |   `-- x
|       `-- gopkg.in
|           |-- fsnotify
|           |-- natefinch
|           `-- stack.v0@v0.0.0-20141108040640-9b43fcefddd0
`-- src

18 directories, 0 files

$/root/go> revel version
Revel executing: displays the Revel Framework and Go version
WARN  06:57:35 version.go:71: Unable to extract version information from Revel library LOG15_ERROR="Normalized odd number of arguments by adding nil"  error,err=nil
Revel Framework :       Unknown (0.21.0 remote master branch)
Revel Cmd       :       0.21.1  (0.21.1 remote master branch)
Revel Modules   :       Unknown (0.21.0 remote master branch)

go version go1.12.9 linux/amd64

revel -v version
INFO  06:58:26   revel.go:94: Import path is absolute or not specified path=
INFO  06:58:26 command_config.go:133: Checking import path /root/go with /root/go
INFO  06:58:26   revel.go:94: Returned import path                     path= buildpath=/root/go
Revel executing: displays the Revel Framework and Go version
INFO  06:58:26  revel.go:104: InitGoPaths
INFO  06:58:26  revel.go:104: Source root                              path=/root/go cwd=/root/go gopath=/root/go bestpath=
INFO  06:58:26  revel.go:104: Set application path                      path=/root/go/src
INFO  06:58:26  revel.go:107: InitPackageResolver                      useVendor=false path=/root/go/src
INFO  06:58:26  revel.go:109: Requesting version information           config="&{Index:7 Verbose:[true] FrameworkVersion:<nil> CommandVersion:<nil> HistoricMode:false ImportPath: GoPath:/root/go GoCmd:/usr/bin/go SrcRoot:/root/go/src AppPath:/root/go/src AppName: Vendored:false PackageResolver:0x64b780 BuildFlags:[] New:{ImportPath: SkeletonPath: Vendored:false Run:false} Build:{TargetPath: ImportPath: Mode: CopySource:false} Run:{ImportPath: Mode: Port:-1 NoProxy:false} Package:{TargetPath: Mode: ImportPath: CopySource:false} Clean:{ImportPath:} Test:{Mode: ImportPath: Function:} Version:{ImportPath: Update:false}}"
INFO  06:58:26 version.go:238: Seeking remote package                   using= remote=github.com/revel/revel
INFO  06:58:26 version.go:238: Resolved called Seeking remote package   remote=github.com/revel/revel  using=
INFO  06:58:26   file.go:358: Request for package                      use vendor=false  package=github.com/revel/revel
INFO  06:58:26   file.go:358: No vendor folder detected, not using dependency manager to import package package=github.com/revel/revel
INFO  06:58:26   file.go:358: Go get command                            exec=/usr/bin/go dir=/root/go/src args="[/usr/bin/go get -u github.com/revel/revel]" env="[GOPATH=/root/go GOROOT=/usr/local/go XDG_SESSION_ID=436 HOSTNAME=uvm-acenode-19.fbi.h-da.de SELINUX_ROLE_REQUESTED= TERM=xterm-256color SHELL=/bin/bash HISTSIZE=1000 SSH_CLIENT=2001:67c:2184:41a::5 54707 22 SELINUX_USE_CURRENT_RANGE= OLDPWD=/root/go/src SSH_TTY=/dev/pts/0 USER=root LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45: GO111MODULE=on MAIL=/var/spool/mail/root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/go/bin PWD=/root/go LANG=C.UTF-8 SELINUX_LEVEL_REQUESTED= HISTCONTROL=ignoredups SHLVL=1 HOME=/root LOGNAME=root SSH_CONNECTION=2001:67c:2184:41a::5 54707 2001:67c:2184:ee5:21a:4aff:fe16:161 22 LESSOPEN=||/usr/bin/lesspipe.sh %s XDG_RUNTIME_DIR=/run/user/0 _=/root/go/bin/revel]" package=github.com/revel/revel
WARN  06:58:29 version.go:71: Unable to extract version information from Revel library  error,err=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO  06:58:29 version.go:99: Got version file                         from=https://raw.githubusercontent.com/revel/revel/master/version.go content="// Copyright (c) 2012-2018 The Revel Framework Authors, All rights reserved.\n// Revel Framework source code and usage is governed by a MIT style\n// license that can be found in the LICENSE file.\n\npackage revel\n\nconst (\n\t// Version current Revel version\n\tVersion = \"0.21.0\"\n\n\t// BuildDate latest commit/release date\n\tBuildDate = \"2018-10-30\"\n\n\t// MinimumGoVersion minimum required Go version for Revel\n\tMinimumGoVersion = \">= go1.8\"\n)\n"
INFO  06:58:29 version.go:99: Got version file                         content="// Copyright (c) 2012-2018 The Revel Framework Authors, All rights reserved.\n// Revel Framework source code and usage is governed by a MIT style\n// license that can be found in the LICENSE file.\n\npackage cmd\n\nconst (\n\t// Version current Revel version\n\tVersion = \"0.21.1\"\n\n\t// BuildDate latest commit/release date\n\tBuildDate = \"2018-10-30\"\n\n\t// MinimumGoVersion minimum required Go version for Revel\n\tMinimumGoVersion = \">= go1.8\"\n)\n"  from=https://raw.githubusercontent.com/revel/cmd/master/version.go
INFO  06:58:29 version.go:99: Got version file                         from=https://raw.githubusercontent.com/revel/modules/master/version.go content="// Copyright (c) 2012-2018 The Revel Framework Authors, All rights reserved.\n// Revel Framework source code and usage is governed by a MIT style\n// license that can be found in the LICENSE file.\n\npackage modules\n\nconst (\n\t// Version current Revel version\n\tVersion = \"0.21.0\"\n\n\t// BuildDate latest commit/release date\n\tBuildDate = \"2018-10-30\"\n\n\t// MinimumGoVersion minimum required Go version for Revel\n\tMinimumGoVersion = \">= go1.8\"\n)\n"
Revel Framework :       Unknown (0.21.0 remote master branch)
Revel Cmd       :       0.21.1  (0.21.1 remote master branch)
Revel Modules   :       Unknown (0.21.0 remote master branch)
```

Any Ideas?

**Comment by yulivee** [comment]
just tested with a new package:
```
# revel -v new myapp
INFO  20:57:57   revel.go:94: Returned import path                     path=myapp buildpath=/root/go
Revel executing: create a skeleton Revel application
INFO  20:57:57  revel.go:104: InitGoPaths
INFO  20:57:57  revel.go:104: Source root                              gopath=/root/go bestpath=/root/go  path= cwd=/root/go
INFO  20:57:57  revel.go:104: Set application path                      path=/root/go/src/myapp
INFO  20:57:57  revel.go:107: InitPackageResolver                      useVendor=false path=/root/go/src/myapp
INFO  20:57:57   file.go:313: error opening directory: open /root/go/src/myapp: no such file or directory
INFO  20:57:57     new.go:70: Detected skeleton path                    path=https://github.com/revel/skeletons:basic/bootstrap4
INFO  20:57:57    new.go:233: Exec:                                    args="[git clone https://github.com/revel/skeletons /tmp/revel/skeleton]"
INFO  20:57:58    new.go:187: Request for package                      package=github.com/revel/revel use vendor=false
INFO  20:57:58    new.go:187: No vendor folder detected, not using dependency manager to import package  package=github.com/revel/revel
INFO  20:57:58    new.go:187: Go get command                            exec=/usr/bin/go dir=/root/go/src/myapp args="[/usr/bin/go get -u github.com/revel/revel]" env="[GOPATH=/root/go GOROOT=/usr/local/go XDG_SESSION_ID=452 HOSTNAME=uvm-acenode-19.fbi.h-da.de SELINUX_ROLE_REQUESTED= TERM=xterm-256color SHELL=/bin/bash HISTSIZE=1000 SSH_CLIENT=2001:67c:2184:41a::7 63338 22 SELINUX_USE_CURRENT_RANGE= OLDPWD=/root SSH_TTY=/dev/pts/0 USER=root GO111MODULE=on MAIL=/var/spool/mail/root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/go/bin PWD=/root/go LANG=C.UTF-8 SELINUX_LEVEL_REQUESTED= HISTCONTROL=ignoredups SHLVL=1 HOME=/root LOGNAME=root SSH_CONNECTION=2001:67c:2184:41a::7 63338 2001:67c:2184:ee5:21a:4aff:fe16:161 22 LESSOPEN=||/usr/bin/lesspipe.sh %s XDG_RUNTIME_DIR=/run/user/0 _=/root/go/bin/revel]" package=github.com/revel/revel
INFO  20:58:00 command_config.go:301: Seeking app package                      app=myapp
INFO  20:58:00 command_config.go:301: Seeking remote package                   using=myapp remote=github.com/revel/revel
INFO  20:58:00 command_config.go:301: Resolved called Seeking remote package   using=myapp remote=github.com/revel/revel
INFO  20:58:00   file.go:358: Request for package                      package=github.com/revel/revel use vendor=false
INFO  20:58:00   file.go:358: No vendor folder detected, not using dependency manager to import package package=github.com/revel/revel
INFO  20:58:00   file.go:358: Go get command                            exec=/usr/bin/go dir=/root/go/src/myapp args="[/usr/bin/go get -u github.com/revel/revel]" env="[GOPATH=/root/go GOROOT=/usr/local/go XDG_SESSION_ID=452 HOSTNAME=uvm-acenode-19.fbi.h-da.de SELINUX_ROLE_REQUESTED= TERM=xterm-256color SHELL=/bin/bash HISTSIZE=1000 SSH_CLIENT=2001:67c:2184:41a::7 63338 22 SELINUX_USE_CURRENT_RANGE= OLDPWD=/root SSH_TTY=/dev/pts/0 USER=root GO111MODULE=on MAIL=/var/spool/mail/root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/go/bin PWD=/root/go LANG=C.UTF-8 SELINUX_LEVEL_REQUESTED= HISTCONTROL=ignoredups SHLVL=1 HOME=/root LOGNAME=root SSH_CONNECTION=2001:67c:2184:41a::7 63338 2001:67c:2184:ee5:21a:4aff:fe16:161 22 LESSOPEN=||/usr/bin/lesspipe.sh %s XDG_RUNTIME_DIR=/run/user/0 _=/root/go/bin/revel]" package=github.com/revel/revel
Your application has been created in:
   /root/go/src/myapp

You can run it with:
   revel run -a  myapp
```

same error
```
# revel run -a  myapp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63f9c1]

goroutine 1 [running]:
github.com/revel/cmd/utils.FindSrcPaths(0x7ffe4847568d, 0x5, 0x926b9f, 0x16, 0x0, 0xc0000c2cf0, 0x0, 0x0, 0x4, 0x4, ...)
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/utils/file.go:358 +0x481
github.com/revel/cmd/model.(*CommandConfig).SetVersions(0xc00000c1e0, 0x925702, 0x14)
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/model/command_config.go:301 +0xcb
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc00000c1e0, 0x8, 0x2)
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/model/command_config.go:154 +0x685
main.main()
        /root/go/pkg/mod/github.com/revel/cmd@v0.21.1/revel/revel.go:94 +0x161
```

**Comment by naqvis** [comment]
@yulivee I went with fresh installation of CentOS 7 box on GCE and followed your provided instructions and couldn't reproduce the problem.
```SHELL
$ go version
go version go1.12.9 linux/amd64
```
```SHELL
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ali/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ali/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build199166616=/tmp/go-build -gno-record-gcc-switches"
```
```SHELL
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
```
```SHELL
$/home/ali/go/> tree -L 4
.
├── bin
│   └── revel
├── pkg
│   └── linux_amd64
│       └── github.com
│           └── revel
└── src
    ├── github.com
    │   ├── agtorre
    │   │   └── gocolorize
    │   ├── inconshreveable
    │   │   └── log15
    │   ├── jessevdk
    │   │   └── go-flags
    │   ├── mattn
    │   │   ├── go-colorable
    │   │   └── go-isatty
    │   ├── pkg
    │   │   └── errors
    │   ├── revel
    │   │   ├── cmd
    │   │   ├── config
    │   │   ├── log15
    │   │   ├── pathtree
    │   │   └── revel
    │   ├── twinj
    │   │   └── uuid
    │   └── xeonx
    │       └── timeago
    ├── golang.org
    │   └── x
    │       ├── net
    │       └── sys
    └── gopkg.in
        ├── fsnotify
        │   └── fsnotify.v1
        ├── natefinch
        │   └── lumberjack.v2
        └── stack.v0
            ├── format_test.go
            ├── LICENSE.md
            ├── README.md
            ├── stack12.go
            ├── stack13.go
            ├── stack.go
            ├── stackinternal_test.go
            └── stack_test.go

38 directories, 9 files
```
```SHELL
$ revel version
Revel executing: displays the Revel Framework and Go version
Revel Framework	:	0.21.0	(0.21.0 remote master branch)
Revel Cmd	:	0.21.1	(0.21.1 remote master branch)
Revel Modules	:	0.21.0	(0.21.0 remote master branch)

go version go1.12.9 linux/amd64
```
```SHELL
$ revel -v version
INFO  17:38:24   revel.go:94: Import path is absolute or not specified path=
INFO  17:38:24 command_config.go:133: Checking import path /home/ali with /home/ali/go
INFO  17:38:24   revel.go:94: Returned import path                     path= buildpath=/home/ali/go
Revel executing: displays the Revel Framework and Go version
INFO  17:38:24  revel.go:104: InitGoPaths
INFO  17:38:24  revel.go:104: Source root                               path=/home/ali/go cwd=/home/ali gopath=/home/ali/go bestpath=
INFO  17:38:24  revel.go:104: Set application path                     path=/home/ali/go/src
INFO  17:38:24  revel.go:107: InitPackageResolver                      useVendor=false path=/home/ali/go/src
INFO  17:38:24  revel.go:109: Requesting version information           config="&{Index:7 Verbose:[true] FrameworkVersion:<nil> CommandVersion:<nil> HistoricMode:false ImportPath: GoPath:/home/ali/go GoCmd:/usr/local/go/bin/go SrcRoot:/home/ali/go/src AppPath:/home/ali/go/src AppName: Vendored:false PackageResolver:0x64bac0 BuildFlags:[] New:{ImportPath: SkeletonPath: Vendored:false Run:false} Build:{TargetPath: ImportPath: Mode: CopySource:false} Run:{ImportPath: Mode: Port:-1 NoProxy:false} Package:{TargetPath: Mode: ImportPath: CopySource:false} Clean:{ImportPath:} Test:{Mode: ImportPath: Function:} Version:{ImportPath: Update:false}}"
INFO  17:38:24 version.go:238: Seeking remote package                   using= remote=github.com/revel/revel
INFO  17:38:24 version.go:71: Fullpath to revel                        dir=/home/ali/go/src/github.com/revel/revel
INFO  17:38:24 version.go:245: Fullpath to revel                         dir=/home/ali/go/src/github.com/revel/revel
INFO  17:38:24 version.go:250: Seeking remote package                   using= remote=github.com/revel/modules
INFO  17:38:24 version.go:256: Fullpath to revel                        dir=/home/ali/go/src/github.com/revel/modules
INFO  17:38:24 version.go:99: Got version file                         content="// Copyright (c) 2012-2018 The Revel Framework Authors, All rights reserved.\n// Revel Framework source code and usage is governed by a MIT style\n// license that can be found in the LICENSE file.\n\npackage revel\n\nconst (\n\t// Version current Revel version\n\tVersion = \"0.21.0\"\n\n\t// BuildDate latest commit/release date\n\tBuildDate = \"2018-10-30\"\n\n\t// MinimumGoVersion minimum required Go version for Revel\n\tMinimumGoVersion = \">= go1.8\"\n)\n"  from=https://raw.githubusercontent.com/revel/revel/master/version.go
INFO  17:38:24 version.go:99: Got version file                         from=https://raw.githubusercontent.com/revel/cmd/master/version.go content="// Copyright (c) 2012-2018 The Revel Framework Authors, All rights reserved.\n// Revel Framework source code and usage is governed by a MIT style\n// license that can be found in the LICENSE file.\n\npackage cmd\n\nconst (\n\t// Version current Revel version\n\tVersion = \"0.21.1\"\n\n\t// BuildDate latest commit/release date\n\tBuildDate = \"2018-10-30\"\n\n\t// MinimumGoVersion minimum required Go version for Revel\n\tMinimumGoVersion = \">= go1.8\"\n)\n"
INFO  17:38:24 version.go:99: Got version file                         from=https://raw.githubusercontent.com/revel/modules/master/version.go content="// Copyright (c) 2012-2018 The Revel Framework Authors, All rights reserved.\n// Revel Framework source code and usage is governed by a MIT style\n// license that can be found in the LICENSE file.\n\npackage modules\n\nconst (\n\t// Version current Revel version\n\tVersion = \"0.21.0\"\n\n\t// BuildDate latest commit/release date\n\tBuildDate = \"2018-10-30\"\n\n\t// MinimumGoVersion minimum required Go version for Revel\n\tMinimumGoVersion = \">= go1.8\"\n)\n"
Revel Framework	:	0.21.0	(0.21.0 remote master branch)
Revel Cmd	:	0.21.1	(0.21.1 remote master branch)
Revel Modules	:	0.21.0	(0.21.0 remote master branch)

go version go1.12.9 linux/amd64
```
```SHELL
$ revel -v new myapp
INFO  17:40:30   revel.go:94: Returned import path                     path=myapp buildpath=/home/ali/go
Revel executing: create a skeleton Revel application
INFO  17:40:30  revel.go:104: InitGoPaths
INFO  17:40:30  revel.go:104: Source root                               path= cwd=/home/ali/go gopath=/home/ali/go bestpath=/home/ali/go
INFO  17:40:30  revel.go:104: Set application path                     path=/home/ali/go/src/myapp
INFO  17:40:30  revel.go:107: InitPackageResolver                      useVendor=false path=/home/ali/go/src/myapp
INFO  17:40:30   file.go:313: error opening directory: open /home/ali/go/src/myapp: no such file or directory
INFO  17:40:30     new.go:70: Detected skeleton path                   path=https://github.com/revel/skeletons:basic/bootstrap4
INFO  17:40:30    new.go:233: Exec:                                    args="[git clone https://github.com/revel/skeletons /tmp/revel/skeleton]"
INFO  17:40:30 command_config.go:301: Seeking app package                       app=myapp
INFO  17:40:30 command_config.go:301: Seeking remote package                   remote=github.com/revel/revel  using=myapp
INFO  17:40:30    new.go:130: Fullpath to revel                        dir=/home/ali/go/src/
INFO  17:40:30    new.go:130: Parsed revel version                     version="Version: 0.21.0\nBuild Date: \n Minimium Go Version: "
Your application has been created in:
   /home/ali/go/src/myapp

You can run it with:
   revel run -a  myapp
```
```SHELL
$ revel run -a myapp
Revel executing: run a Revel application
WARN  17:40:54    run.go:150: No http.addr specified in the app.conf listening on localhost interface only. This will not allow external access to your application
INFO  17:40:56    app     run.go:26: Running revel server
INFO  17:40:56    app revel_hooks.go:32: Go to /@tests to run the tests.
Revel engine is listening on.. localhost:41227
Revel proxy is listening, point your browser to : 9000
```

**Comment by notzippy** [comment]
One very import thing to note here - you should never run an application in production using revel. Use the `revel`  package command to build an artifact to deploy.
