### ISSUE TITLE
Testing Get and Booking Example Error

### ISSUE THREAD

**Issue by icywaffle** [revel/revel#1477]
The first issue that I ran into, trying to copy the [Booking example](https://github.com/revel/examples/blob/master/booking/app/controllers/app_test.go) in order to use `go test` for full coverage. When I was trying to use the [Get method](https://github.com/revel/revel/blob/master/testing/testsuite.go#L107) for the testing suite, it would instantly give me a 

```
revel  panic.go:522: Recovered error in startup                error="runtime error: invalid memory address or nil pointer dereference"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: Fatal error in startup
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x631651]
```

After a few hours of debugging, I finally realized that this was actually the correct response for the test, because it was actually the Get method was appending the wrong URI, causing a panic into a test failure.

What I had to do was actually use [GetCustom](https://github.com/revel/revel/blob/master/testing/testsuite.go#L112), and used this instead.

```
import(
	gotest "testing"
	"github.com/revel/modules/server-engine/gohttptest/testsuite"
)
func TestForGETRequests(t *gotest.T) {
	suite := testsuite.NewTestSuite(t)
	t.Log(suite.Host())
	url := "http://" + suite.Host() + "/somePath"
	suite.GetCustom(url)
}
```

However, the Get method works normally using "github.com/revel/revel/testing" from the main page tutorial, but I think it's better to use this way to get test coverage.

I was wondering why this was an issue, and if anyone ran into this issue too, I hope it helps.

**Comment by icywaffle** [comment]
At a closer look, GetCustom looked like it worked, but it actually does nothing. We don't get a response to decode, because there was nothing that decoded the response. When adding .Send() method at the end of it, it panics again.

Here is the stack trace,
```
goroutine 21 [running]:
github.com/revel/revel.Run.func1()
        C:/Users/Spots/go/src/github.com/revel/revel/server.go:70 +0x158
panic(0xaeac60, 0x11f6140)
        C:/Programming Languages/Go/src/runtime/panic.go:522 +0x1c3
net/url.(*URL).String(0x0, 0x85e578, 0xc000144448)
        C:/Programming Languages/Go/src/net/url/url.go:777 +0x51
ffxiv-profit-api/app.glob..func1(0xc00029a820, 0xc000144490, 0xd, 0xe)
        C:/Users/Spots/go/src/ffxiv-profit-api/app/init.go:65 +0xac
github.com/revel/revel.glob..func33(0xc00029a820, 0xc000144488, 0xe, 0xf)
        C:/Users/Spots/go/src/github.com/revel/revel/watcher.go:298 +0x84
github.com/revel/revel.handleInternal(0xd42bc0, 0xc000293060)
        C:/Users/Spots/go/src/github.com/revel/revel/server-engine.go:193 +0x3b9
github.com/revel/modules/server-engine/gohttptest/testsuite.(*GoHttpServer).Handle(0xc000278e40, 0xd4b800, 0xc0001a6e00, 0xc0003f7900)
        C:/Users/Spots/go/src/github.com/revel/modules/server-engine/gohttptest/testsuite/engine_adapter_go_httptest.go:108 +0x381
github.com/revel/modules/server-engine/gohttptest/testsuite.(*GoHttpServer).Start(0xc000278e40)
        C:/Users/Spots/go/src/github.com/revel/modules/server-engine/gohttptest/testsuite/engine_adapter_go_httptest.go:73 +0x98
github.com/revel/revel.Run(0xffffffffffffffff)
        C:/Users/Spots/go/src/github.com/revel/revel/server.go:88 +0x228
ffxiv-profit-api/app/tmp/run.Run(0xffffffffffffffff)
        C:/Users/Spots/go/src/test-application/app/tmp/run/run.go:28 +0x37
github.com/revel/modules/server-engine/gohttptest/testsuite.RevelTestHelper.func2(0xbcb950)
        C:/Users/Spots/go/src/github.com/revel/modules/server-engine/gohttptest/testsuite/test_helper.go:53 +0x36
created by github.com/revel/modules/server-engine/gohttptest/testsuite.RevelTestHelper
        C:/Users/Spots/go/src/github.com/revel/modules/server-engine/gohttptest/testsuite/test_helper.go:52 +0x283
```

**Comment by icywaffle** [comment]
This also doesn't work for any of the other HTTP methods.

**Comment by brendensoares** [comment]
@icywaffle did you find a solution? If not, can you reproduce the issue with a new revel app (`revel new testapp`)?
