### ISSUE TITLE
Revel run in window Not Support ?

### ISSUE THREAD

**Issue by hewei-github** [revel/revel#1479]
## revel version
Revel executing: displays the Revel Framework and Go version
WARN  17:02:15 version.go:71: Unable to extract version information from Revel library  error,err=nil LOG15_ERROR="Normalized odd
number of arguments by adding nil"
Revel Framework :       Unknown (0.21.0 remote master branch)
Revel Cmd       :       0.21.1  (0.21.1 remote master branch)
Revel Modules   :       Unknown (0.21.0 remote master branch)

go version go1.13.1 windows/amd64

## when run new project 

C:\workpaces\envs\golib>revel run -v -a newApp
INFO  17:04:45   revel.go:94: Returned import path                     path=newApp buildpath=C:\\workpaces\\envs\\golib
INFO  17:04:45 command_config.go:301: Seeking app package                      app=newApp
INFO  17:04:45 command_config.go:301: Seeking remote package                   remote=github.com/revel/revel  using=newApp
INFO  17:04:45 command_config.go:301: Resolved called Seeking remote package   using=newApp remote=github.com/revel/revel
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x642c5c]

goroutine 1 [running]:
github.com/revel/cmd/utils.FindSrcPaths(0xc00001c100, 0x6, 0x93d490, 0x16, 0x0, 0xc0000f4990, 0x0, 0x0, 0x4, 0x4, ...)
        C:/workpaces/envs/goenv/pkg/mod/github.com/revel/cmd@v0.21.1/utils/file.go:358 +0x3dc
github.com/revel/cmd/model.(*CommandConfig).SetVersions(0xc0000021e0, 0x93bd72, 0x14)
        C:/workpaces/envs/goenv/pkg/mod/github.com/revel/cmd@v0.21.1/model/command_config.go:301 +0xd1
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc0000021e0, 0x17, 0x3)
        C:/workpaces/envs/goenv/pkg/mod/github.com/revel/cmd@v0.21.1/model/command_config.go:154 +0x5f5
main.main()
        C:/workpaces/envs/goenv/pkg/mod/github.com/revel/cmd@v0.21.1/revel/revel.go:94 +0x16f

**Comment by hewei-github** [comment]
create new project is ok , but can't run !

**Comment by hewei-github** [comment]
Conf dir has not been modified

**Comment by hewei-github** [comment]
i try install  revel/cmd 3 times 
`C:\workpaces\coding\golang\src\github.com>go get -u github.com/revel/cmd
go: finding github.com/revel/cmd v0.21.1
go: downloading github.com/revel/cmd v0.21.1
go: extracting github.com/revel/cmd v0.21.1
`

**Comment by hewei-github** [comment]
![image](https://user-images.githubusercontent.com/12059788/70223205-3fb36780-1786-11ea-9d4b-cb8442266d2a.png)

**Comment by hewei-github** [comment]
![image](https://user-images.githubusercontent.com/12059788/70223278-670a3480-1786-11ea-9dea-26ff82354e26.png)

**Comment by hewei-github** [comment]
if you revel framework  version read in file or net error ! why not build in binary cmd ?

**Comment by brendensoares** [comment]
Thanks @hewei-github!

This looks like a similar issue I've seen in another issue. I've labeled this so we can add it to our queue of issues. Currently, it looks like a bug in Revel.
