### ISSUE TITLE
Issue looking for GitHub app when running

### ISSUE THREAD

**Issue by bejayoharen** [revel/revel#1532]
I have recently updated to revel 1.0, and my colleague pulled the changes. However, when it came time to run it, things got weird:

```
$ revel run -a .
Revel executing: run a Revel application
Changed detected, recompiling
Parsing packages, (may require download if not cached)...ERROR 15:57:14 harness.go:239: Build detected an error                   error="lstat /Applications/GitHub.app: no such file or directory"
panic: opps
goroutine 31 [running]:
github.com/revel/cmd/utils.(*SourceError).Error(0x0, 0x15bedda, 0x17)
	***gocode/pkg/mod/github.com/revel/cmd@v1.0.3/utils/error.go:49 +0x3ca
github.com/revel/cmd/harness.(*Harness).refresh(0xc000199570, 0x0)
	***gocode/pkg/mod/github.com/revel/cmd@v1.0.3/harness/harness.go:245 +0x6ab
github.com/revel/cmd/harness.(*Harness).Refresh(0xc000199570, 0xc000126ec0)
	***gocode/pkg/mod/github.com/revel/cmd@v1.0.3/harness/harness.go:210 +0xc6
created by github.com/revel/cmd/harness.(*Harness).Run
	***gocode/pkg/mod/github.com/revel/cmd@v1.0.3/harness/harness.go:302 +0x1fa
```

we eventually resolved this by using the GitHub Desktop app, and the following commands:

```
$ mkdir /Applications/GitHub.app/
$ mkdir /Applications/GitHub.app/Contents/
$ mkdir /Applications/GitHub.app/Contents/Resources/
$ cp -r /Applications/GitHub\ Desktop.app/Contents/Resources/app/git /Applications/GitHub.app/Contents/Resources/git
```

I don't know how to reproduce, since it doesn't happen on my machine, but it seems like a bug that revel is expecting expecting to find /Applications/GitHub.app, and I'm hoping that's useful to you even without more info.

**Comment by notzippy** [comment]
The `opps` error indicates a Error was call on a nil error object Which was done in [this](https://github.com/revel/cmd/pull/210/commits/6dba0c3d2df3143c247e7f38e28f2fc5d2a0e629) bad line of code
revel/cmd#210 fixes the error
