### ISSUE TITLE
`revel run -a myapp` doesn't work(From Creating a new Revel application)

### ISSUE THREAD

**Issue by yuki12321** [revel/revel#1577]
[Creating a new Revel application](https://revel.github.io/tutorial/createapp.html)
I tried running the above in a docker golang container.
However, the result is different from what I expected.
Is there any solution?
Thank you for the great development.

```shell
root@f7db23552294:/home/me/gostuff#  revel run -a myapp
Revel executing: run a Revel application
Change detected, recompiling
Parsing packages, (may require download if not cached)...panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6daa4f]

goroutine 323 [running]:
go/types.(*Checker).handleBailout(0xc000552800, 0xc000717c60)
        /usr/local/go/src/go/types/check.go:367 +0x88
panic({0x950300?, 0xdf3660?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xabc7e8, 0xdfb680})
        /usr/local/go/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xabc7e8?, 0xdfb680?})
        /usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xabe668, 0xdd1be0}, 0xc000552800, 0xdfb680, 0xc0007168f0)
        /usr/local/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc000552800, 0xc000025740, 0xdfb680)
        /usr/local/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc000552800, 0xc000025740, {0xabc7e8, 0xdfb680})
        /usr/local/go/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).assignment(0xc000552800, 0xc000025740, {0xabc7e8, 0xdfb680}, {0x9dd95e, 0xa})
        /usr/local/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).assignVar(0xc000552800, {0xabce90, 0xc00013eab0}, {0xabcdd0, 0xc00053ab80}, 0x0, {0x9dd95e, 0xa})
        /usr/local/go/src/go/types/assignments.go:260 +0x1d8
go/types.(*Checker).assignVars(0xc000552800, {0xc0003a0360?, 0x1, 0xc000594ff0?}, {0xc0003a0370, 0xc00070c7e8?, 0x2?})
        /usr/local/go/src/go/types/assignments.go:455 +0x310
go/types.(*Checker).stmt(0xc000552800, 0x0, {0xabd700, 0xc0002e0e40})
        /usr/local/go/src/go/types/stmt.go:476 +0x1628
go/types.(*Checker).stmtList(0xc000552800, 0x0, {0xc0002e0e80?, 0x0?, 0xe?})
        /usr/local/go/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc000552800, 0xabc950?, {0xc0004f22dc?, 0xc0003a1b50?}, 0xc0000b1740, 0xc000595140, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x331
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:852 +0x3a
go/types.(*Checker).processDelayed(0xc000552800, 0x0)
        /usr/local/go/src/go/types/check.go:467 +0x162
go/types.(*Checker).checkFiles(0xc000552800, {0xc0000a00b8, 0x1, 0x1})
        /usr/local/go/src/go/types/check.go:411 +0x1cc
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001e4000, 0xc0002b0700)
        /root/src/pkg/mod/golang.org/x/tools@v0.1.10/go/packages/packages.go:966 +0x76f
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /root/src/pkg/mod/golang.org/x/tools@v0.1.10/go/packages/packages.go:803 +0x1a9
sync.(*Once).doSlow(0x90a226f672e6563?, 0x6e674922090a2c5d?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x726f732209090a2c?, 0x315f6c706d695f74?)
        /root/src/pkg/mod/golang.org/x/tools@v0.1.10/go/packages/packages.go:791 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x65746e692209090a?)
        /root/src/pkg/mod/golang.org/x/tools@v0.1.10/go/packages/packages.go:798 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 262
        /root/src/pkg/mod/golang.org/x/tools@v0.1.10/go/packages/packages.go:797 +0x94
```

```shell
root@f7db23552294:/home/me/gostuff# go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/me/gostuff/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/me/gostuff'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build92698888=/tmp/go-build -gno-record-gcc-switches'
```

```shell
root@f7db23552294:/home/me/gostuff#  revel version
Revel executing: displays the Revel Framework and Go version
Revel Framework :       Unknown (1.1.0 remote master branch)
Revel Cmd       :       1.1.2   (1.1.2 remote master branch)
Revel Modules   :       Unknown (1.1.0 remote master branch)


Go Location:/usr/local/go/bin/go

go version go1.22.4 linux/amd64
```

**Comment by mydreamdoctor** [comment]
I get the same error. Two weeks and no response suggests this is yet another dead Go web framework. What has happened to this language? Has everyone dropped Go in favour of Rust or something?

**Comment by Laur1nMartins** [comment]
I had the same issue starting the revel app using golang 1.22.x or 1.23.0

Using 1.21 seems to work though so please try that.

**Comment by Laur1nMartins** [comment]
From my knowledge fully fledged webframeworks in golang are simply no longer needed. The standard library provides everything you need as detailed in this [article](https://go.dev/doc/articles/wiki/).

More discussions around all of this can be found [here](https://www.reddit.com/r/golang/comments/11044h8/best_web_sever_framework/).

**Comment by Laur1nMartins** [comment]
The issue seems to be with the `golang.org/x/tools`. Upgrading that in the go.mod file of the revel/cmd seems to fix the issue. 

https://github.com/revel/cmd/issues/224

**Comment by mydreamdoctor** [comment]
> The issue seems to be with the `golang.org/x/tools`. Upgrading that in the go.mod file of the revel/cmd seems to fix the issue.
> 
> [revel/cmd#224](https://github.com/revel/cmd/issues/224)

Thank you. Unfortunately the bigger issue appears to be that the project was abandoned more than two years ago, and using an abandoned framework for anything important would be unwise.

**Comment by brendensoares** [comment]
Hello all. I'll take a look at revel/cmd#224 today.

@baylf2000 I'd like to get into a predictable release cycle for Revel. The challenge has always been coordinating volunteer effort. We lost our last volunteer over a year ago and I have not had the time to do anything myself.

The focus should be stability at this point. New features are not currently a priority, though the last major changes we mad to the code was to increase modularity of the various drivers, so we can extend functionality in the future.

If anyone wants to join the core team, let me know.

**Comment by mydreamdoctor** [comment]
@brendensoares Thanks for the reply. I completely understand the difficult issues around resourcing for open source projects such as this. It's a difficulty that every project has to deal with at some point. Some with success. Others not.

At the same time, it's unfortunate that a brilliant project such as this is left in a state where beginner users are presented with a simple tutorial to begin using the project which is now completely broken. It leaves users wondering if they're doing something wrong, and potentially spending large amounts of time trying to fix something that they cannot.

Can I suggest perhaps a large note on the landing page for the project stating that the tutorial instructions are currently broken and should not be attempted?

**Comment by yuki2006** [comment]
I was a user of Revel. I want to express my gratitude to Revel, but it seems that I will hold back from adopting Revel in new projects. However, as a mature technology, I hope that the projects I am currently using will be updated to support newer language versions and so on.

**Comment by gpmn** [comment]
git clone https://github.com/revel/cmd 
then 
cd cmd
then 
go get -u -t ./...
then
go install .

the new revel cmd should works

**Comment by mydreamdoctor** [comment]
> git clone https://github.com/revel/cmd then cd cmd then go get -u -t ./... then go install .
> 
> the new revel cmd should works

The project has been abandoned for at least FOUR YEARS. It would be very unwise to use it for anything important at this point.
