### ISSUE TITLE
panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by lenw** [revel/revel#528]
After upgrading to 0.9.0 I get 

```
INFO  2014/02/26 15:53:03 revel.go:320: Loaded module static
INFO  2014/02/26 15:53:03 revel.go:320: Loaded module testrunner
INFO  2014/02/26 15:53:03 revel.go:320: Loaded module jobs
INFO  2014/02/26 15:53:03 main.go:33: Running revel server
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
runtime.panic(0x4558160, 0xc2100489c0)
    /Users/len/Projects/go/src/pkg/runtime/panic.c:266 +0xb6
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/len/Projects/go/src/pkg/reflect/value.go:1698 +0x79
github.com/revel/revel.findControllers(0x5727ea8, 0x461e2c0, 0xc210048980, 0x1, 0x1)
    /Users/len/Projects/gw/src/github.com/revel/revel/controller.go:294 +0x25a
github.com/revel/revel.RegisterController(0x4618b80, 0x0, 0xc210099480, 0x5, 0x5)
    /Users/len/Projects/gw/src/github.com/revel/revel/controller.go:373 +0x1f3
main.main()
    /Users/len/Projects/gw/src/github.com/CloudAfrica/cog/app/tmp/main.go:81 +0x822

goroutine 3 [syscall]:
runtime.goexit()
    /Users/len/Projects/go/src/pkg/runtime/proc.c:1394
```

**Comment by imuneer** [comment]
@lenw I had the same exact issue.. Removing the pointer same as you described, worked for me.
thanks

**Comment by NtwariJoshua** [comment]
the error is caused by a embedding a non pointer value of the revel.Controller struct
