### ISSUE TITLE
Embedding Non-struct types causes panic

### ISSUE THREAD

**Issue by RMiB** [revel/revel#944]
I have found no limits to the documentation on the use of variable functions:
```
type DBF func() *DBConn

type Admin struct {
	*revel.Controller
	DBF
}
```

When  starting an error occurs:

```
panic: reflect: call of reflect.Value.NumField on func Value

goroutine 1 [running]:
reflect.flag.mustBe(0xd3, 0x19)
        /usr/local/go/src/reflect/value.go:195 +0xb8
reflect.Value.NumField(0x9025a0, 0xc20807b7c8, 0xd3, 0x7faadf3c6b68)
        /usr/local/go/src/reflect/value.go:1117 +0x31
github.com/revel/revel.findControllers(0x7faadf3c6b68, 0x937e60, 0xc2080b84a0, 0x1, 0x1)
        /home/mezencevrv/misc/mygo/src/github.com/revel/revel/controller.go:326 +0x31d
github.com/revel/revel.RegisterController(0x939f20, 0x0, 0xc20808cf00, 0x5, 0x5)
        /home/mezencevrv/misc/mygo/src/github.com/revel/revel/controller.go:400 +0x2c0
main.main()
        /home/mezencevrv/misc/mygo/src/qm-admin/app/tmp/main.go:151 +0x1c2c
```

**Comment by anonx** [comment]
Can confirm anonymous embedding of `non-struct` types causes a panic.
Steps to reproduce:

* Create a new Revel app.
* Create a new type and embed it into controller. For example:
```go
// Test may have any type (e.g. string, bool, float64, or WhatSoEver)
type Test int

// App is a default controller with embedded Test type.
type App struct {
	*revel.Controller
	Test
}
```
* Run the app.
* ...
* PROFIT!

**Comment by jeevatkm** [comment]
I have investigated, harness is not an issue. Problem is at [NumField()](https://github.com/revel/revel/blob/master/controller.go#L326) call for non-struct embedded fields.

**Comment by jeevatkm** [comment]
Taken care!
